const V='v11-rest';
const SUPABASE_URL='https://bztigwfnenwosulhxrxo.supabase.co';
const SUPABASE_KEY='sb_publishable_P76ca2ta_N7PWpA_Wm6lTw__DEzK19l';
const API=SUPABASE_URL+'/rest/v1/';
let tab='mekan';
let state={me:null,venues:[],check:null,candidates:[],match:null,messages:[],error:null};
function app(){return document.getElementById('app')}
function save(k,v){localStorage.setItem('ca_'+k,JSON.stringify(v))}
function load(k,d){try{let v=localStorage.getItem('ca_'+k);return v?JSON.parse(v):d}catch(e){return d}}
function deviceId(){let x=load('device',null);if(!x){x='dev_'+Math.random().toString(36).slice(2)+'_'+Date.now();save('device',x)}return x}
function esc(s){return String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function api(table,params={},opt={}){let u=new URL(API+table);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v));let r=await fetch(u.toString(),{method:opt.method||'GET',headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+SUPABASE_KEY,'Content-Type':'application/json',...(opt.headers||{})},body:opt.body?JSON.stringify(opt.body):undefined});let t=await r.text();let d=t?JSON.parse(t):null;if(!r.ok)throw new Error((d&&d.message)||t||r.statusText);return d}
async function safe(p){try{return {data:await p,error:null}}catch(e){return {data:null,error:e}}}
function header(){return `<div class='top'><div><p class='eyebrow'>Cesme sosyal check-in</p><h1 class='brand'>CesmeAsk</h1></div><div class='logo'>💙</div></div>`}
function tabs(){let items=[['mekan','📍 Mekan'],['kesfet','💫 Kesfet'],['chat','💬 Chat'],['profil','👤 Profil']];document.getElementById('tabs').innerHTML=items.map(i=>`<button class='tab ${tab===i[0]?'on':''}' onclick="setTab('${i[0]}')">${i[1]}</button>`).join('')}
function statusLine(){return state.error?`<div class='warn'>Hata: ${esc(state.error)}</div>`:`<div class='ok'>Canli DB bagli · ${V}</div>`}
async function init(){app().innerHTML=header()+`<article class='card hero'><h2>Yukleniyor...</h2><p class='muted'>DB baglantisi kontrol ediliyor.</p></article>`;await loadMe();await loadVenues();await loadActiveCheck();draw()}
async function loadMe(){let r=await safe(api('profiles',{select:'*',device_id:'eq.'+deviceId(),limit:'1'}));if(r.error){state.error=r.error.message;return}state.me=(r.data&&r.data[0])||load('me',null)}
async function loadVenues(){let r=await safe(api('venues',{select:'*',order:'name.asc'}));if(r.error){state.error=r.error.message;state.venues=[];return}let c=await safe(api('checkins',{select:'venue_id',expires_at:'gt.'+new Date().toISOString()}));let counts={};(c.data||[]).forEach(x=>counts[x.venue_id]=(counts[x.venue_id]||0)+1);state.venues=(r.data||[]).map(v=>({...v,total:counts[v.id]||0}))}
async function loadActiveCheck(){if(!state.me||!state.me.id){state.check=null;return}let r=await safe(api('checkins',{select:'*,venues(*)',profile_id:'eq.'+state.me.id,expires_at:'gt.'+new Date().toISOString(),order:'created_at.desc',limit:'1'}));state.check=(r.data&&r.data[0])||null}
function draw(){tabs();if(!state.me||!state.me.id)return onboard();if(tab==='mekan')return mekan();if(tab==='kesfet')return kesfet();if(tab==='chat')return chat();profil()}
function setTab(t){tab=t;if(t==='mekan')loadVenues().then(draw);else if(t==='kesfet')loadCandidates().then(draw);else if(t==='chat')loadChat().then(draw);else draw()} window.setTab=setTab;
function onboard(){app().innerHTML=header()+`<article class='card hero'><h2>Ayni mekandasiniz. Tanismak karsilikliysa baslasin.</h2><p class='muted'>Profilin Supabase'e kaydolacak. Tam konum yok, sadece mekan check-in.</p>${statusLine()}<label>Ad<input id='name' placeholder='Onur'></label><label>Yas<input id='age' type='number' placeholder='19'></label><label>Bio<input id='bio' placeholder='Kahve + deniz + sohbet'></label><button class='btn' id='start'>Basla</button></article>`;document.getElementById('start').onclick=saveProfile}
async function saveProfile(){let p={device_id:deviceId(),display_name:document.getElementById('name').value||'Onur',age:Number(document.getElementById('age').value||19),bio:document.getElementById('bio').value||'Cesme deyim, iyi sohbet iyi gider.',gender:'',interests:['kahve','deniz','sohbet']};let r=await safe(api('profiles',{on_conflict:'device_id',select:'*'},{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:p}));if(r.error){state.error=r.error.message;return draw()}state.me=Array.isArray(r.data)?r.data[0]:r.data;save('me',state.me);tab='mekan';await loadVenues();draw()}
function venueStats(){let total=state.venues.reduce((a,v)=>a+(v.total||0),0);let hot=[...state.venues].sort((a,b)=>(b.total||0)-(a.total||0))[0];return {total,hot}}
function mekan(){let s=venueStats();let c=state.check;let html=header()+`<article class='card'><h2>Bugun nerdesin?</h2><p class='muted'>Mekan secince check-in Supabase'e yazilir.</p>${statusLine()}<div class='row'><div class='stat'><b>${s.total}</b>check-in</div><div class='stat'><b>${state.venues.length}</b>mekan</div><div class='stat'><b>${s.hot?esc(s.hot.name):'-'}</b>hot</div></div>${c?`<p class='ok'>Check-in: ${esc(c.venues?.name||c.venue_id)}</p><button class='btn red' id='endCheck'>Check-in bitir</button>`:`<p class='warn'>Aktif check-in yok.</p>`}</article>`;state.venues.forEach(v=>{html+=`<button class='venue' data-id='${esc(v.id)}'><span class='emoji'>${esc(v.emoji||'📍')}</span><span><b>${esc(v.name)}</b><br><small>${esc(v.area)} · ${esc(v.category)}</small></span><span class='right'>${v.total||0} kisi<br>Canli</span></button>`});app().innerHTML=html;document.querySelectorAll('.venue').forEach(b=>b.onclick=()=>checkin(b.dataset.id));let e=document.getElementById('endCheck');if(e)e.onclick=endCheckin}
async function checkin(venue_id){await safe(api('checkins',{profile_id:'eq.'+state.me.id,expires_at:'gt.'+new Date().toISOString()},{method:'PATCH',headers:{Prefer:'return=minimal'},body:{expires_at:new Date().toISOString()}}));let r=await safe(api('checkins',{select:'*'},{method:'POST',headers:{Prefer:'return=representation'},body:{profile_id:state.me.id,venue_id}}));if(r.error){state.error=r.error.message;return draw()}state.check=Array.isArray(r.data)?r.data[0]:r.data;state.check.venues=state.venues.find(v=>v.id===venue_id);tab='kesfet';await loadCandidates();draw()}
async function endCheckin(){await safe(api('checkins',{profile_id:'eq.'+state.me.id,expires_at:'gt.'+new Date().toISOString()},{method:'PATCH',headers:{Prefer:'return=minimal'},body:{expires_at:new Date().toISOString()}}));state.check=null;await loadVenues();draw()}
async function loadCandidates(){state.candidates=[];if(!state.check)return;let r=await safe(api('checkins',{select:'profile_id,venue_id,profiles(id,device_id,display_name,age,bio,interests,gender)',venue_id:'eq.'+state.check.venue_id,expires_at:'gt.'+new Date().toISOString(),profile_id:'neq.'+state.me.id,order:'created_at.desc'}));if(r.error){state.error=r.error.message;return}let sw=await safe(api('swipes',{select:'swiped_id',swiper_id:'eq.'+state.me.id,venue_id:'eq.'+state.check.venue_id}));let seen=new Set((sw.data||[]).map(x=>x.swiped_id));state.candidates=(r.data||[]).map(x=>x.profiles).filter(p=>p&&!seen.has(p.id))}
function kesfet(){if(!state.check){app().innerHTML=header()+`<article class='card'><h2>Once mekana check-in yap</h2><button class='btn' onclick="setTab('mekan')">Mekan sec</button></article>`;return}if(!state.candidates.length){app().innerHTML=header()+`<article class='card'><h2>Bu mekanda yeni kisi yok</h2><p class='muted'>Baska telefondan ayni mekana girince burada gorunecek.</p><button class='btn' onclick='loadCandidates().then(draw)'>Yenile</button><button class='btn light' onclick="setTab('mekan')">Mekan degistir</button></article>`;return}let p=state.candidates[0];let tags=(p.interests||[]).map(t=>`<span class='pill'>${esc(t)}</span>`).join('');app().innerHTML=header()+`<section class='person'><h2>${esc(p.display_name)}, ${esc(p.age||'')}</h2><p>${esc(p.bio||'')}</p><div>${tags}</div></section><div class='actions'><button class='round' onclick="swipe('${p.id}','nope')">❌</button><button class='round' onclick="swipe('${p.id}','like')">💙</button></div>`}
async function makeMatch(target,venue_id){let a=[state.me.id,target].sort();let r=await safe(api('matches',{on_conflict:'user_a,user_b,venue_id',select:'*'},{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:{user_a:a[0],user_b:a[1],venue_id}}));if(r.error){state.error=r.error.message;return false}let m=Array.isArray(r.data)?r.data[0]:r.data;state.match=m;save('match',m);await safe(api('messages',{},{method:'POST',headers:{Prefer:'return=minimal'},body:{match_id:m.id,sender_id:target,body:'Selam, ayni mekandayiz sanirim 😄'}}));alert('Match oldu!');tab='chat';await loadChat();draw();return true}
async function swipe(target,action){let venue_id=state.check.venue_id;await safe(api('swipes',{on_conflict:'swiper_id,swiped_id,venue_id'},{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:{swiper_id:state.me.id,swiped_id:target,venue_id,action}}));if(action==='like'){await makeMatch(target,venue_id);return}await loadCandidates();draw()}
async function loadChat(){state.match=load('match',null);state.messages=[];if(!state.me)return;let r=await safe(api('matches',{select:'*',or:`(user_a.eq.${state.me.id},user_b.eq.${state.me.id})`,order:'created_at.desc',limit:'1'}));if(r.data&&r.data[0]){state.match=r.data[0];save('match',state.match)}if(state.match){let m=await safe(api('messages',{select:'*',match_id:'eq.'+state.match.id,order:'created_at.asc'}));state.messages=m.data||[]}}
function chat(){if(!state.match){app().innerHTML=header()+`<article class='card'><h2>Henuz match yok</h2><p class='muted'>Like atinca demo match acilir.</p><button class='btn' onclick="setTab('kesfet')">Kesfet</button></article>`;return}let msgs=state.messages.map(m=>`<div class='msg ${m.sender_id===state.me.id?'me':''}'>${esc(m.body)}</div>`).join('')||`<div class='msg'>Match acildi. Ilk mesaji sen at 😄</div>`;app().innerHTML=header()+`<article class='card'><h2>Canli chat</h2>${msgs}<label>Mesaj<input id='msg' placeholder='Selam'></label><button class='btn' id='send'>Gonder</button><button class='btn light' onclick='loadChat().then(draw)'>Yenile</button></article>`;document.getElementById('send').onclick=sendMsg}
async function sendMsg(){let body=document.getElementById('msg').value.trim();if(!body)return;await safe(api('messages',{},{method:'POST',headers:{Prefer:'return=minimal'},body:{match_id:state.match.id,sender_id:state.me.id,body}}));await loadChat();draw()}
function profil(){let m=state.me;app().innerHTML=header()+`<article class='card'><h2>${esc(m.display_name)}, ${esc(m.age||'')}</h2><p class='muted'>${esc(m.bio||'')}</p><p class='ok'>Profil Supabase'de kayitli.</p><button class='btn red' onclick='resetApp()'>Bu cihazdaki oturumu sifirla</button></article>`}
function resetApp(){localStorage.clear();location.href='/?fresh='+Date.now()} window.resetApp=resetApp; window.swipe=swipe;
window.addEventListener('DOMContentLoaded',init);
