const V='v10-supabase';
const SUPABASE_URL='https://bztigwfnenwosulhxrxo.supabase.co';
const SUPABASE_KEY='sb_publishable_P76ca2ta_N7PWpA_Wm6lTw__DEzK19l';
const db=window.supabase?window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY):null;
let tab='mekan';
let state={me:null,venues:[],check:null,candidates:[],idx:0,match:null,messages:[],error:null};
function app(){return document.getElementById('app')}
function save(k,v){localStorage.setItem('ca_'+k,JSON.stringify(v))}
function load(k,d){try{let v=localStorage.getItem('ca_'+k);return v?JSON.parse(v):d}catch(e){return d}}
function id(){let x=load('device',null);if(!x){x='dev_'+Math.random().toString(36).slice(2)+'_'+Date.now();save('device',x)}return x}
function esc(s){return String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function header(){return `<div class='top'><div><p class='eyebrow'>Cesme sosyal check-in</p><h1 class='brand'>CesmeAsk</h1></div><div class='logo'>💙</div></div>`}
function tabs(){let items=[['mekan','📍 Mekan'],['kesfet','💫 Kesfet'],['chat','💬 Chat'],['profil','👤 Profil']];document.getElementById('tabs').innerHTML=items.map(i=>`<button class='tab ${tab===i[0]?'on':''}' onclick="setTab('${i[0]}')">${i[1]}</button>`).join('')}
function statusLine(){if(state.error)return `<div class='warn'>Supabase hata: ${esc(state.error)}</div>`;return `<div class='ok'>Canli DB bagli · ${V}</div>`}
async function q(p){try{return await p}catch(e){return {data:null,error:e}}}
async function init(){tabs();if(!db){state.error='Supabase kutuphanesi yuklenmedi';return renderShell()}await loadMe();await loadVenues();await loadActiveCheck();draw()}
async function loadMe(){let device_id=id();let r=await q(db.from('profiles').select('*').eq('device_id',device_id).maybeSingle());if(r.error){state.error=r.error.message;return}state.me=r.data||load('me',null)}
async function loadVenues(){let r=await q(db.from('venues').select('*').order('name'));if(r.error){state.error=r.error.message;state.venues=[];return}state.venues=r.data||[];let c=await q(db.from('checkins').select('venue_id').gt('expires_at',new Date().toISOString()));let counts={};(c.data||[]).forEach(x=>counts[x.venue_id]=(counts[x.venue_id]||0)+1);state.venues=state.venues.map(v=>({...v,total:counts[v.id]||0}))}
async function loadActiveCheck(){if(!state.me||!state.me.id){state.check=null;return}let r=await q(db.from('checkins').select('*,venues(*)').eq('profile_id',state.me.id).gt('expires_at',new Date().toISOString()).order('created_at',{ascending:false}).limit(1).maybeSingle());state.check=r.data||null}
function renderShell(){app().innerHTML=header()+`<article class='card hero'><h2>CesmeAsk</h2><p class='muted'>Supabase baglantisi hazirlaniyor.</p>${statusLine()}<button class='btn' onclick='location.reload()'>Yenile</button></article>`}
function draw(){tabs();if(!state.me||!state.me.id)return onboard();if(tab==='mekan')return mekan();if(tab==='kesfet')return kesfet();if(tab==='chat')return chat();profil()}
function setTab(t){tab=t;if(t==='mekan')loadVenues().then(draw);else if(t==='kesfet')loadCandidates().then(draw);else if(t==='chat')loadChat().then(draw);else draw()} window.setTab=setTab;
function onboard(){app().innerHTML=header()+`<article class='card hero'><h2>Ayni mekandasiniz. Tanismak karsilikliysa baslasin.</h2><p class='muted'>Profilin Supabase'e kaydolacak. Tam konum yok, sadece mekan check-in.</p>${statusLine()}<label>Ad<input id='name' placeholder='Onur'></label><label>Yas<input id='age' type='number' placeholder='19'></label><label>Bio<input id='bio' placeholder='Kahve + deniz + sohbet'></label><button class='btn' id='start'>Basla</button></article>`;document.getElementById('start').onclick=saveProfile}
async function saveProfile(){let payload={device_id:id(),display_name:document.getElementById('name').value||'Onur',age:Number(document.getElementById('age').value||19),bio:document.getElementById('bio').value||'Cesme deyim, iyi sohbet iyi gider.',gender:'',interests:['kahve','deniz','sohbet']};let r=await q(db.from('profiles').upsert(payload,{onConflict:'device_id'}).select().single());if(r.error){state.error=r.error.message;return draw()}state.me=r.data;save('me',state.me);tab='mekan';await loadVenues();draw()}
function venueStats(){let total=state.venues.reduce((a,v)=>a+(v.total||0),0);let hot=[...state.venues].sort((a,b)=>(b.total||0)-(a.total||0))[0];return {total,hot}}
function mekan(){let s=venueStats();let c=state.check;let html=header()+`<article class='card'><h2>Bugun nerdesin?</h2><p class='muted'>Mekan secince check-in Supabase'e yazilir. Arkadasin baska telefondan girerse ayni mekanda gorunur.</p>${statusLine()}<div class='row'><div class='stat'><b>${s.total}</b>check-in</div><div class='stat'><b>${state.venues.length}</b>mekan</div><div class='stat'><b>${s.hot?esc(s.hot.name):'-'}</b>hot</div></div>${c?`<p class='ok'>Check-in: ${esc(c.venues?.name||c.venue_id)}</p><button class='btn red' id='endCheck'>Check-in bitir</button>`:`<p class='warn'>Aktif check-in yok.</p>`}</article>`;state.venues.forEach(v=>{html+=`<button class='venue' data-id='${esc(v.id)}'><span class='emoji'>${esc(v.emoji||'📍')}</span><span><b>${esc(v.name)}</b><br><small>${esc(v.area)} · ${esc(v.category)}</small></span><span class='right'>${v.total||0} kisi<br>Canli</span></button>`});app().innerHTML=html;document.querySelectorAll('.venue').forEach(b=>b.onclick=()=>checkin(b.dataset.id));let e=document.getElementById('endCheck');if(e)e.onclick=endCheckin}
async function checkin(venue_id){if(!state.me){tab='profil';return draw()}await q(db.from('checkins').update({expires_at:new Date().toISOString()}).eq('profile_id',state.me.id).gt('expires_at',new Date().toISOString()));let r=await q(db.from('checkins').insert({profile_id:state.me.id,venue_id}).select('*,venues(*)').single());if(r.error){state.error=r.error.message;return draw()}state.check=r.data;tab='kesfet';await loadCandidates();draw()}
async function endCheckin(){await q(db.from('checkins').update({expires_at:new Date().toISOString()}).eq('profile_id',state.me.id));state.check=null;await loadVenues();draw()}
async function loadCandidates(){state.candidates=[];if(!state.check){return}let r=await q(db.from('checkins').select('profile_id,venue_id,profiles(id,device_id,display_name,age,bio,interests,gender)').eq('venue_id',state.check.venue_id).gt('expires_at',new Date().toISOString()).neq('profile_id',state.me.id).order('created_at',{ascending:false}));if(r.error){state.error=r.error.message;return}let sw=await q(db.from('swipes').select('swiped_id').eq('swiper_id',state.me.id).eq('venue_id',state.check.venue_id));let seen=new Set((sw.data||[]).map(x=>x.swiped_id));state.candidates=(r.data||[]).map(x=>x.profiles).filter(p=>p&&!seen.has(p.id));state.idx=0}
function kesfet(){if(!state.check){app().innerHTML=header()+`<article class='card'><h2>Once mekana check-in yap</h2><button class='btn' onclick="setTab('mekan')">Mekan sec</button></article>`;return}if(!state.candidates.length){app().innerHTML=header()+`<article class='card'><h2>Bu mekanda yeni kisi yok</h2><p class='muted'>Baska telefondan ayni mekana girince burada gorunecek.</p><button class='btn' onclick='loadCandidates().then(draw)'>Yenile</button><button class='btn light' onclick="setTab('mekan')">Mekan degistir</button></article>`;return}let p=state.candidates[state.idx%state.candidates.length];let tags=(p.interests||[]).map(t=>`<span class='pill'>${esc(t)}</span>`).join('');app().innerHTML=header()+`<section class='person'><h2>${esc(p.display_name)}, ${esc(p.age||'')}</h2><p>${esc(p.bio||'')}</p><div>${tags}</div></section><div class='actions'><button class='round' onclick="swipe('${p.id}','nope')">❌</button><button class='round' onclick="swipe('${p.id}','like')">💙</button></div>`}
async function makeMatch(target,venue_id){let a=[state.me.id,target].sort();let m=await q(db.from('matches').upsert({user_a:a[0],user_b:a[1],venue_id},{onConflict:'user_a,user_b,venue_id'}).select('*').single());if(m.data){state.match=m.data;save('match',m.data);await q(db.from('messages').insert({match_id:m.data.id,sender_id:target,body:'Selam, ayni mekandayiz sanirim 😄'}));alert('Match oldu!');tab='chat';await loadChat();draw();return true}return false}
async function swipe(target,action){let venue_id=state.check.venue_id;await q(db.from('swipes').upsert({swiper_id:state.me.id,swiped_id:target,venue_id,action},{onConflict:'swiper_id,swiped_id,venue_id'}));if(action==='like'){let cand=state.candidates.find(p=>p.id===target);let isDemo=cand&&String(cand.device_id||'').startsWith('demo_');let rev=await q(db.from('swipes').select('id').eq('swiper_id',target).eq('swiped_id',state.me.id).eq('venue_id',venue_id).eq('action','like').maybeSingle());if(isDemo||rev.data){let done=await makeMatch(target,venue_id);if(done)return}}await loadCandidates();draw()}
async function loadChat(){let local=load('match',null);state.match=local;state.messages=[];if(!state.me)return;let r=await q(db.from('matches').select('*').or(`user_a.eq.${state.me.id},user_b.eq.${state.me.id}`).order('created_at',{ascending:false}).limit(1).maybeSingle());if(r.data){state.match=r.data;save('match',r.data)}if(state.match){let m=await q(db.from('messages').select('*').eq('match_id',state.match.id).order('created_at',{ascending:true}));state.messages=m.data||[]}}
function chat(){if(!state.match){app().innerHTML=header()+`<article class='card'><h2>Henuz match yok</h2><p class='muted'>Karsilikli like olunca chat acilir.</p><button class='btn' onclick="setTab('kesfet')">Kesfet</button></article>`;return}let msgs=state.messages.map(m=>`<div class='msg ${m.sender_id===state.me.id?'me':''}'>${esc(m.body)}</div>`).join('')||`<div class='msg'>Match acildi. Ilk mesaji sen at 😄</div>`;app().innerHTML=header()+`<article class='card'><h2>Canli chat</h2>${msgs}<label>Mesaj<input id='msg' placeholder='Selam, ayni mekandayiz sanirim'></label><button class='btn' id='send'>Gonder</button><button class='btn light' onclick='loadChat().then(draw)'>Yenile</button></article>`;document.getElementById('send').onclick=sendMsg}
async function sendMsg(){let body=document.getElementById('msg').value.trim();if(!body)return;await q(db.from('messages').insert({match_id:state.match.id,sender_id:state.me.id,body}));await loadChat();draw()}
function profil(){let m=state.me;app().innerHTML=header()+`<article class='card'><h2>${esc(m.display_name)}, ${esc(m.age||'')}</h2><p class='muted'>${esc(m.bio||'')}</p><p class='ok'>Profil Supabase'de kayitli.</p><button class='btn red' onclick='resetApp()'>Bu cihazdaki oturumu sifirla</button></article>`}
function resetApp(){localStorage.clear();location.href='/?fresh='+Date.now()} window.resetApp=resetApp; window.swipe=swipe;
window.addEventListener('DOMContentLoaded',init);
