(function(){
if(window.__chatMapFix)return;window.__chatMapFix=1;
var API=window.API||'https://bztigwfnenwosulhxrxo.supabase.co/rest/v1/';
var KEY=window.KEY||'sb_publishable_P76ca2ta_N7PWpA_Wm6lTw__DEzK19l';
function q(id){return document.getElementById(id)}
function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function safe(s){return String(s||'').replace(/[,()]/g,'')}
function clean(s){return String(s||'').toLowerCase().replace(/[^a-z0-9_]/g,'').slice(0,20)}
function prof(){try{return JSON.parse(localStorage.ca_profile||'{}')}catch(e){return {}}}
function dev(){var p=prof();var d=p.device_id||localStorage.ca_device_stable||localStorage.ca_device;if(!d){d='dev_'+Math.random().toString(36).slice(2)+'_'+Date.now();localStorage.ca_device_stable=d;localStorage.ca_device=d}return d}
window.dev=dev;
async function api(path,params,opt){var u=new URL(API+path);Object.keys(params||{}).forEach(function(k){u.searchParams.set(k,params[k])});var h={apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json',Prefer:'return=representation'};var r=await fetch(u,{method:(opt&&opt.method)||'GET',headers:h,body:opt&&opt.body?JSON.stringify(opt.body):undefined});var t=await r.text();var d=t?JSON.parse(t):null;if(!r.ok)throw Error((d&&d.message)||t||r.statusText);return d}
function css(){if(q('cmfStyle'))return;var s=document.createElement('style');s.id='cmfStyle';s.textContent='.cmfChatList{display:grid;gap:10px}.cmfChat{display:flex;gap:12px;align-items:center;background:#fff;border:1px solid #dbeafe;border-radius:24px;padding:12px;box-shadow:0 12px 30px #07598518}.cmfChat b{font-size:16px}.cmfAvatar{width:54px;height:54px;border-radius:18px;object-fit:cover;background:#e0f2fe;display:grid;place-items:center;font-weight:950;color:#075985}.cmfStatus{font-size:12px;font-weight:900;color:#64748b}.cmfOpen{width:auto!important;margin:0!important;padding:10px 13px!important}.cmfPanel{background:linear-gradient(135deg,#082f49,#0ea5e9);color:white;border-radius:24px;padding:14px;margin:10px 0}.cmfPanel button{width:auto;border:0;border-radius:999px;padding:10px 13px;margin:4px;font-weight:950}.cmfCheck{background:#fb923c;color:white}.cmfDetail{background:#e0f2fe;color:#075985}.cmfOk{background:#dcfce7;color:#166534;border-radius:16px;padding:11px;margin:8px 0}.cmfBad{background:#fee2e2;color:#991b1b;border-radius:16px;padding:11px;margin:8px 0}.cmfMsgs{background:#f8fafc;border:1px solid #dbeafe;border-radius:22px;padding:10px;max-height:300px;overflow:auto}.cmfMsg{background:#e0f2fe;border-radius:18px;padding:10px 12px;margin:7px 0;max-width:82%}.cmfMsg.me{background:#dcfce7;margin-left:auto}.cmfInput{display:grid;grid-template-columns:1fr auto;gap:8px;margin-top:8px}.leaflet-popup-content .cmfCheck,.leaflet-popup-content .cmfDetail{border:0;border-radius:999px;padding:9px 12px;margin:4px;font-weight:950}';document.head.appendChild(s)}
function av(src){return src?'<img class="cmfAvatar" src="'+esc(src)+'">':'<div class="cmfAvatar">◇</div>'}
async function requireProfile(){var p=prof();if(!p.device_id||!p.user||!p.name){if(window.show)show('profile');alert('Önce Profil sekmesinden Yeni profil oluştur veya Profilime gir.');throw Error('Profil yok')}return p}
window.ensureProfile=requireProfile;
window.loadVenues=async function(){css();try{window.venues=await api('rpc/venues_with_counts',{}, {method:'POST'});if(!window.map){window.map=L.map('map').setView([38.315,26.342],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19}).addTo(window.map)}window.map.eachLayer(function(l){if(l instanceof L.Marker)window.map.removeLayer(l)});window.venues.forEach(function(v){if(!v.lat||!v.lng)return;var html='<b>'+esc(v.name)+'</b><br><span>'+esc(v.area||'Çeşme')+' · '+esc(v.category||'Mekân')+'</span><br><b>'+Number(v.live_count||0)+' kişi burada</b><br><button class="cmfCheck" onclick="cmfCheckin(\''+esc(v.id)+'\')">Buradayım</button><button class="cmfDetail" onclick="cmfVenue(\''+esc(v.id)+'\')">Detaylandır</button>';var m=L.marker([v.lat,v.lng],{icon:pinIcon?pinIcon(v):undefined}).addTo(window.map).bindPopup(html);m.on('click',function(){window.selected=v})})}catch(e){alert('Mekânlar yüklenmedi: '+e.message)}};
window.cmfVenue=function(id){window.selected=(window.venues||[]).find(function(v){return v.id===id});if(!window.selected)return;if(window.selectVenue)selectVenue(id);else if(window.show)show('venue')};
window.cmfCheckin=async function(id){window.selected=(window.venues||[]).find(function(v){return v.id===id});if(!window.selected){alert('Mekân bulunamadı.');return}try{await requireProfile();await api('rpc/device_checkin',{}, {method:'POST',body:{p_device_id:dev(),p_venue_id:window.selected.id}});if(q('venueInfo'))q('venueInfo').innerHTML='<div class="cmfOk"><b>'+esc(window.selected.name)+'</b> için Buradayım aktif. Eski konumun otomatik silindi.</div>';if(window.loadVenues)await loadVenues();if(window.loadPeople)await loadPeople();alert(window.selected.name+' için Buradayım aktif.')}catch(e){alert('Buradayım olmadı: '+e.message)}};
window.quickCheckIn=window.cmfCheckin;
window.checkInSelected=async function(){if(!window.selected){alert('Önce haritadan mekân seç.');return}return window.cmfCheckin(window.selected.id)};
window.msgInvite=async function(username){try{await requireProfile();var res=await api('rpc/room_request_v2',{}, {method:'POST',body:{p_from_device:dev(),p_to_username:clean(username)}});var txt=res&&res.status==='accepted'?'Karşılıklı istek tamam, tek chat açıldı.':'Mesaj isteği gönderildi.';var out=q('msgSearchResults')||q('peopleList');if(out)out.innerHTML='<div class="cmfOk">'+txt+'</div>';if(res&&res.room_id){await cmfOpenChat(res.room_id,username)}else if(window.renderMsg){await renderMsg()}}catch(e){var out=q('msgSearchResults')||q('peopleList');if(out)out.innerHTML='<div class="cmfBad">İstek gitmedi: '+esc(e.message)+'</div>';else alert('İstek gitmedi: '+e.message)}};
window.mvpInviteFromProfile=window.msgInvite;
window.msgAccept=async function(id,u){try{var res=await api('rpc/room_accept_v2',{}, {method:'POST',body:{p_request_id:id,p_my_device:dev()}});if(window.renderMsg)await renderMsg();if(res&&res.room_id)await cmfOpenChat(res.room_id,u||'chat')}catch(e){alert('Kabul olmadı: '+e.message)}};
async function profileMap(devs){devs=[...new Set(devs.filter(Boolean))];if(!devs.length)return {};var rows=await api('profiles',{device_id:'in.('+devs.map(safe).join(',')+')',select:'device_id,username,display_name,photo_url'});var m={};rows.forEach(function(p){m[p.device_id]=p});return m}
async function cmfLoadChats(){var host=q('msgChats');if(!host)return;try{var d=safe(dev());var rooms=await api('direct_rooms',{or:'(device_a.eq.'+d+',device_b.eq.'+d+')',select:'*',order:'created_at.desc'});if(!rooms.length){host.innerHTML='<div class="warn">Henüz özel chat yok. Birine istek gönder veya gelen isteği kabul et.</div>';return}var profs=await profileMap(rooms.map(function(r){return r.device_a===dev()?r.device_b:r.device_a}));host.innerHTML='<div class="cmfChatList">'+rooms.map(function(r){var od=r.device_a===dev()?r.device_b:r.device_a,p=profs[od]||{},u=p.username||od,n=p.display_name||u;return '<div class="cmfChat">'+av(p.photo_url)+'<div style="flex:1"><b>'+esc(n)+'</b><br><span class="cmfStatus">@'+esc(u)+' · tek sohbet odası</span></div><button class="btn light cmfOpen" onclick="cmfOpenChat(\''+esc(r.id)+'\',\''+esc(u)+'\')">Aç</button></div>'}).join('')+'</div>'}catch(e){host.innerHTML='<div class="cmfBad">Chatler yüklenmedi: '+esc(e.message)+'</div>'}}
window.loadChats=cmfLoadChats;
window.cmfOpenChat=async function(room,u){return cmfOpenChat(room,u)};
async function cmfOpenChat(room,u){var box=q('msgChatBox');if(!box)return;box.style.display='block';box.innerHTML='<div class="cmfPanel"><b>@'+esc(u||'chat')+'</b><br><span>Özel sohbet</span></div><div id="cmfMsgs" class="cmfMsgs">Mesajlar yükleniyor...</div><div class="cmfInput"><textarea id="cmfText" rows="2" placeholder="Mesaj yaz..."></textarea><button class="btn" onclick="cmfSend(\''+esc(room)+'\')">Gönder</button></div>';await cmfMsgs(room)}
async function cmfMsgs(room){var box=q('cmfMsgs');if(!box)return;try{var rows=await api('direct_messages',{room_id:'eq.'+room,select:'*',order:'created_at.asc'});box.innerHTML=rows.length?rows.map(function(m){return '<div class="cmfMsg '+(m.sender_device===dev()?'me':'')+'"><b>'+esc(m.sender_name)+'</b><br>'+esc(m.body)+'</div>'}).join(''):'<div class="warn">İlk mesajı yaz.</div>';box.scrollTop=box.scrollHeight}catch(e){box.innerHTML='<div class="cmfBad">Mesajlar gelmedi: '+esc(e.message)+'</div>'}}
window.cmfSend=async function(room){try{await requireProfile();var t=q('cmfText'),body=(t.value||'').trim();if(!body)return;await api('direct_messages',{}, {method:'POST',body:{room_id:room,sender_device:dev(),sender_name:prof().name,body:body.slice(0,800)}});t.value='';await cmfMsgs(room);await cmfLoadChats()}catch(e){alert('Mesaj gitmedi: '+e.message)}};
var oldRender=window.renderMsg;
window.renderMsg=async function(){if(oldRender)await oldRender();await cmfLoadChats()};
var oldShow=window.show;
window.show=function(id){oldShow(id);if(id==='help')setTimeout(function(){if(window.renderMsg)renderMsg()},0);if(id==='map')setTimeout(function(){if(window.loadVenues)loadVenues()},0)};
css();setTimeout(function(){if(window.loadVenues)loadVenues()},600);
})();