(function(){
if(window.__citySelectPatch)return;window.__citySelectPatch=1;
var API='https://bztigwfnenwosulhxrxo.supabase.co/rest/v1/';
var KEY='sb_publishable_P76ca2ta_N7PWpA_Wm6lTw__DEzK19l';
var cities={cesme:{name:'Çeşme',lat:38.323,lng:26.305,z:12},izmir:{name:'İzmir',lat:38.4237,lng:27.1428,z:12},istanbul:{name:'İstanbul',lat:41.0082,lng:28.9784,z:11},ankara:{name:'Ankara',lat:39.9334,lng:32.8597,z:11}};
function q(id){return document.getElementById(id)}
function esc(s){return String(s||'').replace(/[&<>]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[c]})}
function city(){return localStorage.piyasa_city||''}
function setCity(c){localStorage.piyasa_city=c}
async function rpc(path,body){var r=await fetch(API+path,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json'},body:JSON.stringify(body||{})});var t=await r.text();var d=t?JSON.parse(t):null;if(!r.ok)throw Error((d&&d.message)||t||r.statusText);return d}
function css(){if(q('cityStyle'))return;var s=document.createElement('style');s.id='cityStyle';s.textContent='.cityModal{position:fixed;inset:0;z-index:2147483646;background:linear-gradient(135deg,#075985,#0ea5e9,#fb923c);display:grid;place-items:center;padding:20px}.cityBox{background:rgba(255,255,255,.96);border:1px solid #bae6fd;border-radius:32px;padding:22px;width:min(420px,92vw);box-shadow:0 28px 70px rgba(2,6,23,.35);text-align:center}.cityLogo{font-size:42px;font-weight:1000;color:#075985;letter-spacing:-1.5px;margin-bottom:6px}.citySub{color:#64748b;font-weight:900;margin-bottom:16px}.cityGrid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.cityBtn{border:0;border-radius:22px;padding:16px 10px;font-size:17px;font-weight:1000;background:#e0f2fe;color:#075985}.cityBtn.active{background:#0ea5e9;color:white}.citySwitch{position:fixed;top:calc(58px + env(safe-area-inset-top));left:14px;z-index:2147483600;border:0;border-radius:999px;background:rgba(255,255,255,.9);color:#075985;font-weight:1000;padding:8px 11px;border:1px solid #bae6fd;box-shadow:0 10px 24px rgba(2,132,199,.15)}@media(max-width:760px){.citySwitch{top:calc(58px + env(safe-area-inset-top));left:10px;font-size:12px;padding:7px 9px}}';document.head.appendChild(s)}
window.chooseCity=function(c){setCity(c);var m=q('cityModal');if(m)m.remove();if(window.loadVenues)loadVenues();if(window.updateCitySwitch)updateCitySwitch();if(window.show)show('map')}
function showCityModal(force){css();if(q('cityModal'))return;if(city()&&!force)return;var d=document.createElement('div');d.id='cityModal';d.className='cityModal';d.innerHTML='<div class="cityBox"><div class="cityLogo">Piyasa</div><div class="citySub">İlk önce şehrini seç</div><div class="cityGrid">'+Object.keys(cities).map(function(k){return '<button class="cityBtn" onclick="chooseCity(\''+k+'\')">'+esc(cities[k].name)+'</button>'}).join('')+'</div></div>';document.body.appendChild(d)}
window.updateCitySwitch=function(){css();var b=q('citySwitch');if(!b){b=document.createElement('button');b.id='citySwitch';b.className='citySwitch';b.onclick=function(){showCityModal(true)};document.body.appendChild(b)}var c=city()||'cesme';b.textContent='📍 '+(cities[c]||cities.cesme).name;if(q('map')&&getComputedStyle(q('map')).display!=='none')b.style.display='block';else b.style.display='none'}
window.loadVenues=async function(){css();var c=city()||'cesme';setCity(c);try{window.venues=await rpc('rpc/venues_with_counts_city',{p_city:c});var cfg=cities[c]||cities.cesme;var m=window.map||map;if(!m){m=L.map('map').setView([cfg.lat,cfg.lng],cfg.z);window.map=m;map=m;L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19}).addTo(m)}else{m.setView([cfg.lat,cfg.lng],cfg.z)}m.eachLayer(function(l){if(l instanceof L.Marker)m.removeLayer(l)});window.venues.forEach(function(v){if(!v.lat||!v.lng)return;var icon=window.pinIcon?window.pinIcon(v):undefined;var html='<b>'+esc(v.name)+'</b><br><small>'+esc(v.area||'')+' · '+esc(v.category||'Mekan')+'</small><br><b>'+Number(v.live_count||0)+' kişi burada</b><div class="dpRow"><button class="dpBtn dpHere" onclick="window.popupHere(\''+esc(v.id)+'\')">Buradayım</button><button class="dpBtn dpDetail" onclick="window.popupDetail(\''+esc(v.id)+'\')">Detaylandır</button><button class="dpBtn dpLeave" onclick="window.popupNotHere(\''+esc(v.id)+'\')">Burda değilim</button></div>';L.marker([v.lat,v.lng],{icon:icon}).addTo(m).bindPopup(html)});updateCitySwitch();if(window.fixTopLocationLayout)fixTopLocationLayout()}catch(e){alert('Mekanlar yüklenmedi: '+e.message)}}
var oldShow=window.show;window.show=function(id){if(oldShow)oldShow(id);setTimeout(updateCitySwitch,80);if(id==='map'){if(!city())showCityModal(false);setTimeout(function(){if(window.loadVenues)loadVenues()},120)}}
setTimeout(function(){showCityModal(false);updateCitySwitch()},700);
})();