(function(){
if(window.__directPopupActions)return;window.__directPopupActions=1;
var API='https://bztigwfnenwosulhxrxo.supabase.co/rest/v1/';
var KEY='sb_publishable_P76ca2ta_N7PWpA_Wm6lTw__DEzK19l';
function esc(s){return String(s||'').replace(/[&<>]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[c]})}
function q(id){return document.getElementById(id)}
function prof(){try{return JSON.parse(localStorage.ca_profile||'{}')}catch(e){return {}}}
function dev(){var p=prof();return p.device_id||localStorage.ca_device_stable||localStorage.ca_device||''}
async function rpc(path,body){var r=await fetch(API+path,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json'},body:JSON.stringify(body||{})});var t=await r.text();var d=t?JSON.parse(t):null;if(!r.ok)throw Error((d&&d.message)||t||r.statusText);return d}
function need(){var p=prof();if(!p.device_id||!p.user||!p.name){if(window.show)show('profile');alert('Önce profile gir.');throw Error('no profile')}return p}
function findVenue(id){return (window.venues||[]).find(function(v){return v.id===id})||{id:id,name:id}}
function geo(){return new Promise(function(ok,no){if(!navigator.geolocation)return no(Error('Konum desteği yok'));navigator.geolocation.getCurrentPosition(function(p){ok({lat:p.coords.latitude,lng:p.coords.longitude})},function(){no(Error('Konum izni lazım'))},{enableHighAccuracy:true,timeout:12000,maximumAge:15000})})}
function modal(html){var old=q('geoPrivacyModal');if(old)old.remove();var d=document.createElement('div');d.id='geoPrivacyModal';d.style.cssText='position:fixed;inset:0;z-index:2147483647;background:rgba(15,23,42,.45);display:grid;place-items:center;padding:18px';d.innerHTML='<div style="width:min(430px,94vw);background:white;border-radius:28px;padding:16px;box-shadow:0 26px 70px rgba(2,6,23,.35);border:1px solid #dbeafe"><button id="gpmClose" style="float:right;border:0;border-radius:999px;background:#fee2e2;color:#991b1b;font-weight:1000;padding:7px 10px">Kapat</button>'+html+'</div>';document.body.appendChild(d);q('gpmClose').onclick=function(){d.remove()}}
window.popupHere=async function(id){try{need();var v=findVenue(id);var g=await geo();window.selected=v;await rpc('rpc/device_checkin_v3',{p_device_id:dev(),p_venue_id:id,p_lat:g.lat,p_lng:g.lng});if(q('venueInfo'))q('venueInfo').innerHTML='<div class="ok"><b>'+esc(v.name)+'</b> için Buradayım aktif.</div>';if(window.loadVenues)await window.loadVenues();if(window.loadPeople)await window.loadPeople();alert(v.name+' için Buradayım aktif.')}catch(e){alert('Buradayım olmadı: '+e.message)}};
window.popupNotHere=async function(id){try{need();var v=findVenue(id);window.selected=null;await rpc('rpc/leave_venue_v1',{p_device_id:dev()});if(q('venueInfo'))q('venueInfo').innerHTML='<div class="notHereMsg"><b>'+esc(v.name)+'</b> için artık burada değilsin. Hiçbir yer seçili değil.</div>';if(q('peopleList'))q('peopleList').innerHTML='';if(window.loadVenues)await window.loadVenues();alert('Artık burada değilsin.')}catch(e){alert('Burda değilim olmadı: '+e.message)}};
window.popupDetail=async function(id){var v=findVenue(id);window.selected=v;try{var g=await geo();var c=await rpc('rpc/can_view_venue_people_v1',{p_venue_id:id,p_lat:g.lat,p_lng:g.lng});if(!c.can_view){modal('<h2 style="margin:0 0 8px;color:#075985">'+esc(v.name||c.venue_name||'Mekan')+'</h2><p style="font-weight:900;color:#0f172a">Burada <b>'+Number(v.live_count||0)+'</b> kişi var.</p><p style="color:#64748b;font-weight:800">Kişileri görmek için bu mekanın 500 metre içinde olman lazım. Şu an yaklaşık <b>'+esc(c.distance_meters||'?')+' m</b> uzaktasın.</p>');return}if(window.selectVenue)window.selectVenue(id)}catch(e){modal('<h2 style="margin:0 0 8px;color:#075985">'+esc(v.name||'Mekan')+'</h2><p style="font-weight:900;color:#0f172a">Burada <b>'+Number(v.live_count||0)+'</b> kişi var.</p><p style="color:#64748b;font-weight:800">Kişileri görmek için konum izni vermen ve 500 metre içinde olman lazım.</p>')}};
(function style(){if(q('directPopupStyle'))return;var s=document.createElement('style');s.id='directPopupStyle';s.textContent='.dpBtn{border:0;border-radius:999px;padding:9px 11px;margin:4px;font-weight:1000}.dpHere{background:#fb923c;color:white}.dpDetail{background:#e0f2fe;color:#075985}.dpLeave{background:#ef4444;color:white}.dpRow{display:flex;flex-wrap:wrap;gap:4px;margin-top:6px}';document.head.appendChild(s)})();
window.loadVenues=async function(){try{window.venues=await rpc('rpc/venues_with_counts',{});var m=window.map||map;if(!m){m=L.map('map').setView([38.315,26.342],12);window.map=m;map=m;L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19}).addTo(m)}m.eachLayer(function(l){if(l instanceof L.Marker)m.removeLayer(l)});window.venues.forEach(function(v){if(!v.lat||!v.lng)return;var icon=window.pinIcon?window.pinIcon(v):undefined;var html='<b>'+esc(v.name)+'</b><br><small>'+esc(v.area||'Çeşme')+' - '+esc(v.category||'Mekan')+'</small><br><b>'+Number(v.live_count||0)+' kişi burada</b><div class="dpRow"><button class="dpBtn dpHere" onclick="window.popupHere(\''+esc(v.id)+'\')">Buradayım</button><button class="dpBtn dpDetail" onclick="window.popupDetail(\''+esc(v.id)+'\')">Detaylandır</button><button class="dpBtn dpLeave" onclick="window.popupNotHere(\''+esc(v.id)+'\')">Burda değilim</button></div>';L.marker([v.lat,v.lng],{icon:icon}).addTo(m).bindPopup(html)})}catch(e){alert('Mekanlar yüklenmedi: '+e.message)}};
setTimeout(function(){if(window.loadVenues)window.loadVenues()},900);
})();