(function(){
if(window.__piyasaBatch20260616)return;window.__piyasaBatch20260616=1;
var API='https://bztigwfnenwosulhxrxo.supabase.co/rest/v1/';
var KEY='sb_publishable_P76ca2ta_N7PWpA_Wm6lTw__DEzK19l';
function q(s){return document.querySelector(s)}
function qa(s){return Array.prototype.slice.call(document.querySelectorAll(s))}
function txt(x){return String(x||'')}
function prof(){try{return JSON.parse(localStorage.ca_profile||'{}')}catch(e){return {}}}
function hasProfile(){var p=prof();return !!(p.name||p.display_name||p.user||p.username)}
function api(path,body){return fetch(API+path,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json'},body:JSON.stringify(body||{})}).then(function(r){return r.text().then(function(t){var d=t?JSON.parse(t):null;if(!r.ok)throw Error((d&&d.message)||t||r.statusText);return d})})}
function addStyle(){if(q('#piyasaBatchStyle'))return;var s=document.createElement('style');s.id='piyasaBatchStyle';s.textContent=':root{--p1:#0ea5e9;--p2:#8b5cf6;--p3:#fb923c;--p4:#ec4899;--p5:#22c55e}body{background:radial-gradient(circle at 12% 8%,#bae6fd,transparent 30%),radial-gradient(circle at 88% 14%,#fed7aa,transparent 32%),radial-gradient(circle at 60% 96%,#fbcfe8,transparent 28%),linear-gradient(135deg,#ecfeff,#fff7ed)!important}.brand,.panel,.card,.dock,.profileHero{box-shadow:0 18px 48px rgba(14,165,233,.22)!important}.brand{border:1px solid rgba(255,255,255,.75)!important;background:linear-gradient(135deg,rgba(255,255,255,.95),rgba(240,249,255,.9))!important}.brand b{background:linear-gradient(135deg,var(--p1),var(--p2),var(--p3));-webkit-background-clip:text;background-clip:text;color:transparent!important}.panel{border:1px solid rgba(255,255,255,.82)!important;background:rgba(255,255,255,.92)!important}.dock{background:linear-gradient(135deg,#082f49,#075985,#4c1d95)!important}.tab.on,.btn:not(.light){background:linear-gradient(135deg,var(--p1),var(--p2),var(--p3))!important;color:white!important}.card{background:linear-gradient(135deg,rgba(255,255,255,.96),rgba(240,249,255,.9))!important}.pinb{border-color:#8b5cf6!important;background:linear-gradient(135deg,#fff,#eff6ff)!important}.cnt{background:linear-gradient(135deg,#ef4444,#ec4899)!important}.batchChip{display:inline-flex;align-items:center;gap:6px;margin:7px 5px 0 0;padding:7px 10px;border-radius:999px;background:#eff6ff;color:#075985;font-weight:950;font-size:12px}.batchSpeed{position:fixed;left:12px;bottom:calc(86px + env(safe-area-inset-bottom));z-index:2147483000;background:linear-gradient(135deg,#0ea5e9,#8b5cf6);color:white;border-radius:999px;padding:8px 11px;font-size:12px;font-weight:1000;box-shadow:0 14px 34px rgba(14,165,233,.35)}.target{transition:left .09s linear,top .09s linear,transform .07s ease!important}.target:active{transform:scale(.88)!important}';document.head.appendChild(s)}
function fixLogin(){if(!hasProfile())return;localStorage.ca_profile_done='1';localStorage.ca_logged_in='1';var p=prof();if(p.user&&!p.device_id)p.device_id=p.user;if(p.device_id||p.user){localStorage.ca_device_stable=p.device_id||p.user;localStorage.ca_device=p.device_id||p.user}try{localStorage.ca_profile=JSON.stringify(p)}catch(e){}var pe=q('#profileEdit');var pv=q('#profileView');if(pe&&pv&&pv.innerHTML&&pv.innerHTML.indexOf('Düzenleme modu')<0){pe.style.display='none'}qa('input,select,textarea').forEach(function(el){var ph=(el.getAttribute('placeholder')||'').toLowerCase();if(ph.indexOf('kullanıcı')>-1||ph.indexOf('adın')>-1){var box=el.closest('.card')||el.parentElement;if(box&&box.id!=='profileEdit'&&box.innerText&&box.innerText.toLowerCase().indexOf('profil')>-1)box.style.display='none'}})}
function speedVenues(){var old=window.loadVenues;if(typeof old==='function'&&!old.__batch){var last=0,cache=null;window.loadVenues=function(){var now=Date.now();if(cache&&now-last<12000){try{window.venues=cache;if(window.map&&window.map.invalidateSize)window.map.invalidateSize()}catch(e){}return Promise.resolve(cache)}last=now;return Promise.resolve(old.apply(this,arguments)).then(function(r){try{cache=window.venues||cache}catch(e){}return r})};window.loadVenues.__batch=1}}
function syncMorePlaces(){var key='piyasa_place_sync_20260616';if(localStorage[key]&&Date.now()-Number(localStorage[key])<21600000)return;localStorage[key]=Date.now();fetch('/api/sync-cesme-cafes',{method:'POST'}).catch(function(){})}
function fasterButtons(){qa('button').forEach(function(b){if(b.__fast)return;b.__fast=1;b.addEventListener('touchstart',function(){b.style.transform='scale(.97)'},{passive:true});b.addEventListener('touchend',function(){b.style.transform=''},{passive:true})})}
function appPatch(){addStyle();fixLogin();speedVenues();fasterButtons();syncMorePlaces();if(!q('#batchSpeedBadge')&&q('#map')){var d=document.createElement('div');d.id='batchSpeedBadge';d.className='batchSpeed';d.textContent='⚡ Hız modu açık';document.body.appendChild(d);setTimeout(function(){if(d.parentNode)d.remove()},3500)}}
function gamePatch(){if(!q('#arena')||!q('#target'))return;addStyle();if(window.__gameBetter)return;window.__gameBetter=1;var good=['💙','🌊','🍦','🧿','⛵','☀️','🏖️','🔥'];var score=0,time=45,life=3,combo=1,streak=0,playing=false,timer=null,cur='💙',spawn=0;function set(){var a=q('#score'),b=q('#time'),c=q('#life'),m=q('#comboText');if(a)a.textContent=score;if(b)b.textContent=time;if(c)c.textContent=life;if(m)m.textContent='Combo x'+combo}function choose(){var r=Math.random();if(r<.10)return'⭐';if(r<.25)return'💣';return good[Math.floor(Math.random()*good.length)]}function place(){var target=q('#target');cur=choose();spawn=Date.now();target.textContent=cur;target.className='target '+(cur==='💣'?'bad':cur==='⭐'?'gold':'');var size=cur==='⭐'?58:Math.max(46,72-Math.floor(score/120)*4);target.style.width=size+'px';target.style.height=size+'px';target.style.fontSize=Math.max(24,size/2)+'px';target.style.left=(Math.random()*76+8)+'%';target.style.top=(Math.random()*70+10)+'%'}function floatText(t,x,y,ok){var a=q('#arena');if(!a)return;var d=document.createElement('div');d.className='toast';d.style.left=(x||40)+'px';d.style.top=(y||40)+'px';d.style.color=ok?'#16a34a':'#dc2626';d.textContent=t;a.appendChild(d);setTimeout(function(){d.remove()},600)}window.startGame=function(){score=0;time=45;life=3;combo=1;streak=0;playing=true;set();place();clearInterval(timer);timer=setInterval(function(){time--;set();if(time<=0)window.finish&&window.finish()},1000)};window.tapTarget=function(e){if(!playing)return;if(e&&e.stopPropagation)e.stopPropagation();var x=(e&&e.offsetX)||40,y=(e&&e.offsetY)||40;if(cur==='💣'){life--;streak=0;combo=1;score=Math.max(0,score-18);floatText('-18',q('#target').offsetLeft+x,q('#target').offsetTop+y,false);if(life<=0){set();window.finish&&window.finish();return}}else{streak++;combo=Math.min(5,1+Math.floor(streak/5));var pts=cur==='⭐'?35*combo:10*combo;score+=pts;floatText('+'+pts,q('#target').offsetLeft+x,q('#target').offsetTop+y,true)}set();place()};window.finish=function(){if(!playing)return;playing=false;clearInterval(timer);try{window.saveScore&&window.saveScore()}catch(e){}};var arena=q('#arena');if(arena&&!arena.__miss){arena.__miss=1;arena.addEventListener('click',function(e){if(!playing||e.target.id==='target')return;streak=0;combo=1;score=Math.max(0,score-4);set();floatText('combo gitti',e.offsetX,e.offsetY,false)})}var h=q('.hero')||q('.wrap h1');if(h&&!q('#comboText')){var c=document.createElement('span');c.id='comboText';c.className='combo';c.textContent='Combo x1';h.appendChild(c)}if(!q('#life')){var row=q('.row');if(row){var box=document.createElement('div');box.className='card';box.innerHTML='<div>Can</div><div id="life" class="score">3</div>';row.appendChild(box)}}set();place()}
function run(){try{if(q('#map')||q('#profile')||q('#venue'))appPatch();gamePatch()}catch(e){}}
run();setInterval(run,900);
})();
