(function(){
if(window.__dmWindowPatch)return;window.__dmWindowPatch=1;
var API='https://bztigwfnenwosulhxrxo.supabase.co/rest/v1/';
var KEY='sb_publishable_P76ca2ta_N7PWpA_Wm6lTw__DEzK19l';
var active={room:'',user:'',profile:null};
function q(id){return document.getElementById(id)}
function esc(s){return String(s||'').replace(/[&<>]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[c]})}
function safe(s){return String(s||'').replace(/[,()]/g,'')}
function prof(){try{return JSON.parse(localStorage.ca_profile||'{}')}catch(e){return {}}}
function dev(){var p=prof();return p.device_id||localStorage.ca_device_stable||localStorage.ca_device||''}
async function api(path,params,opt){var u=new URL(API+path);Object.keys(params||{}).forEach(function(k){u.searchParams.set(k,params[k])});var r=await fetch(u,{method:(opt&&opt.method)||'GET',headers:{apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json',Prefer:'return=representation'},body:opt&&opt.body?JSON.stringify(opt.body):undefined});var t=await r.text();var d=t?JSON.parse(t):null;if(!r.ok)throw Error((d&&d.message)||t||r.statusText);return d}
function css(){if(q('dmWinStyle'))return;var s=document.createElement('style');s.id='dmWinStyle';s.textContent='.dmWin{height:100%;display:grid;grid-template-rows:auto 1fr auto;background:#f8fafc;border-radius:26px;overflow:hidden;border:1px solid #dbeafe}.dmHead{display:grid;grid-template-columns:auto 48px 1fr;gap:10px;align-items:center;background:white;padding:10px;border-bottom:1px solid #e2e8f0;position:sticky;top:0;z-index:30}.dmBack{border:0;border-radius:999px;background:#e0f2fe;color:#075985;font-weight:1000;padding:10px 12px}.dmAv{width:48px;height:48px;border-radius:50%;object-fit:cover;background:linear-gradient(135deg,#e0f2fe,#dbeafe);display:grid;place-items:center;color:#075985;font-weight:1000;border:2px solid #bae6fd}.dmWho{min-width:0;cursor:pointer}.dmName{font-size:17px;font-weight:1000;color:#0f172a;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dmUser{font-size:12px;color:#64748b;font-weight:900}.dmMsgs{padding:12px;overflow-y:auto;-webkit-overflow-scrolling:touch;display:flex;flex-direction:column;gap:8px}.dmBubble{max-width:78%;padding:10px 12px;border-radius:18px;background:#fee2e2;color:#7f1d1d;align-self:flex-start;word-break:break-word}.dmBubble.me{background:#dbeafe;color:#1e3a8a;align-self:flex-end}.dmMeta{font-size:10px;opacity:.7;font-weight:900;margin-top:4px}.dmDel{border:0;background:rgba(255,255,255,.65);border-radius:999px;font-size:11px;font-weight:1000;margin-top:5px;padding:4px 8px;color:#991b1b}.dmSend{display:grid;grid-template-columns:1fr auto;gap:8px;background:white;border-top:1px solid #e2e8f0;padding:10px}.dmSend textarea{border:1px solid #dbeafe;border-radius:18px;padding:11px;font-weight:800;outline:0;resize:none}.dmSend button{border:0;border-radius:18px;background:#0ea5e9;color:white;font-weight:1000;padding:0 14px}.dmProfile{background:white;border-radius:26px;border:1px solid #dbeafe;padding:14px;box-shadow:0 18px 45px rgba(2,132,199,.12)}.dmHero{background:linear-gradient(135deg,#0ea5e9,#fb923c);color:white;border-radius:24px;padding:16px;display:grid;gap:8px}.dmBigAv{width:88px;height:88px;border-radius:28px;background:white;color:#075985;display:grid;place-items:center;font-size:32px;font-weight:1000;object-fit:cover}.dmPill{display:inline-block;background:rgba(255,255,255,.18);border:1px solid rgba(255,255,255,.28);padding:7px 10px;border-radius:999px;font-weight:900;margin:3px}.dmEmpty{text-align:center;color:#64748b;font-weight:900;padding:20px}.dmTopClickable{display:contents}';document.head.appendChild(s)}
function avatar(p,cls){if(p&&p.photo_url)return '<img class="'+cls+'" src="'+esc(p.photo_url)+'">';return '<div class="'+cls+'">'+esc(((p&&p.display_name)||'◇').slice(0,1).toUpperCase())+'</div>'}
function when(s){if(!s)return '';var d=(Date.now()-new Date(s).getTime())/1000;if(d<60)return 'şimdi';if(d<3600)return Math.floor(d/60)+' dk';if(d<86400)return Math.floor(d/3600)+' sa';return Math.floor(d/86400)+' g'}
async function roomProfile(room,u){var d=dev();var rooms=await api('direct_rooms',{id:'eq.'+safe(room),select:'*',limit:'1'});var r=rooms&&rooms[0];var other=r?(r.device_a===d?r.device_b:r.device_a):'';var rows=[];if(other)rows=await api('profiles',{device_id:'eq.'+safe(other),select:'*',limit:'1'});if(!rows.length&&u)rows=await api('profiles',{username:'eq.'+safe(u),select:'*',limit:'1'});return rows[0]||{username:u||'chat',display_name:u||'Chat'}}
async function loadMsgs(){var box=q('dmMsgs');if(!box||!active.room)return;try{var rows=await api('direct_messages',{room_id:'eq.'+active.room,select:'*',order:'created_at.asc'});box.innerHTML=rows.length?rows.map(function(m){var mine=m.sender_device===dev();var del=mine?'<button class="dmDel" data-del="'+esc(m.id)+'">Sil</button>':'';return '<div class="dmBubble '+(mine?'me':'')+'">'+esc(m.body)+'<div class="dmMeta">'+esc(m.sender_name)+' · '+esc(when(m.created_at))+'</div>'+del+'</div>'}).join(''):'<div class="dmEmpty">İlk mesajı yaz.</div>';box.scrollTop=box.scrollHeight}catch(e){box.innerHTML='<div class="dmEmpty">Mesajlar yüklenmedi.</div>'}}
window.dmBack=function(){if(window.renderMsg)renderMsg()}
window.dmOpenProfile=function(){var p=active.profile||{};var host=q('help');if(!host)return;host.innerHTML='<div class="igWrap"><button class="dmBack" onclick="cmfOpenChat(\''+esc(active.room)+'\',\''+esc(active.user)+'\')">← Mesaja dön</button><div class="dmProfile"><div class="dmHero">'+avatar(p,'dmBigAv')+'<h2 style="margin:0">'+esc(p.display_name||p.username||'Kullanıcı')+'</h2><b>@'+esc(p.username||'')+'</b><p>'+esc(p.bio||'')+'</p><div><span class="dmPill">'+esc(p.gender||'')+'</span><span class="dmPill">'+esc(p.age||'')+' yaş</span></div></div></div></div>';if(window.fitScreensAboveNav)setTimeout(fitScreensAboveNav,80)}
window.cmfOpenChat=async function(room,u){css();active.room=room;active.user=u||'chat';var host=q('help')||document.body;host.innerHTML='<div class="dmWin"><div class="dmHead"><button class="dmBack" id="dmBack">←</button><div id="dmAvHold"></div><div class="dmWho" id="dmWho"><div class="dmName">Yükleniyor...</div><div class="dmUser">@'+esc(active.user)+'</div></div></div><div id="dmMsgs" class="dmMsgs"></div><div class="dmSend"><textarea id="dmText" rows="2" placeholder="Mesaj yaz..."></textarea><button id="dmSendBtn">Gönder</button></div></div>';q('dmBack').onclick=window.dmBack;try{active.profile=await roomProfile(room,u)}catch(e){active.profile={username:u,display_name:u}}var p=active.profile;active.user=p.username||active.user;q('dmAvHold').innerHTML=avatar(p,'dmAv');q('dmWho').innerHTML='<div class="dmName">'+esc(p.display_name||p.username||'Kullanıcı')+'</div><div class="dmUser">@'+esc(p.username||'')+'</div>';q('dmAvHold').onclick=window.dmOpenProfile;q('dmWho').onclick=window.dmOpenProfile;q('dmSendBtn').onclick=window.dmSend;q('dmText').addEventListener('keydown',function(e){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();window.dmSend()}});q('dmMsgs').onclick=function(e){var id=e.target&&e.target.dataset&&e.target.dataset.del;if(id)window.dmDelete(id)};await loadMsgs();if(window.fitScreensAboveNav)setTimeout(fitScreensAboveNav,80)}
window.dmSend=async function(){var t=q('dmText');if(!t)return;var body=(t.value||'').trim();if(!body)return;await api('direct_messages',{}, {method:'POST',body:{room_id:active.room,sender_device:dev(),sender_name:prof().name,body:body.slice(0,800)}});t.value='';await loadMsgs()}
window.dmDelete=async function(id){try{await api('rpc/delete_direct_message_v1',{}, {method:'POST',body:{p_message_id:id,p_device_id:dev()}});await loadMsgs()}catch(e){alert('Mesaj silinemedi: '+e.message)}}
setInterval(function(){if(q('dmMsgs')&&active.room)loadMsgs()},2500);
})();