(function(){
if(window.__fixedBottomBar)return;window.__fixedBottomBar=1;
function q(s){return document.querySelector(s)}
function qa(s){return Array.prototype.slice.call(document.querySelectorAll(s))}
function isNav(el){if(!el)return false;var txt=(el.innerText||'').toLowerCase();var cls=(el.className||'').toString().toLowerCase();var id=(el.id||'').toLowerCase();var keys=['harita','profil','mesaj','rehber','oyun','mekan','map','profile','chat'];var hit=keys.filter(function(k){return txt.indexOf(k)>-1}).length;return hit>=2||cls.indexOf('tab')>-1||cls.indexOf('bottom')>-1||id.indexOf('tab')>-1||id.indexOf('bottom')>-1}
function findBar(){var cands=qa('nav,footer,.tabs,.tabbar,.bottomNav,.bottom-nav,.nav,.menu,.dock,[class*=tab],[class*=bottom]');for(var i=0;i<cands.length;i++){if(isNav(cands[i]))return cands[i]}var all=qa('body *');var best=null,bottom=-1;all.forEach(function(el){var r=el.getBoundingClientRect();if(r.height>35&&r.height<120&&r.width>innerWidth*.45&&r.top>innerHeight*.45&&isNav(el)&&r.top>bottom){best=el;bottom=r.top}});return best}
function fix(){var bar=findBar();if(!bar)return;bar.id=bar.id||'fixedAppBottomBar';bar.style.position='fixed';bar.style.left='10px';bar.style.right='10px';bar.style.bottom='calc(10px + env(safe-area-inset-bottom))';bar.style.zIndex='2147483000';bar.style.transform='none';bar.style.pointerEvents='auto';bar.style.touchAction='manipulation';bar.style.webkitTransform='translateZ(0)';bar.style.backdropFilter='blur(18px)';bar.style.maxWidth='760px';bar.style.margin='0 auto';document.body.style.paddingBottom='calc(110px + env(safe-area-inset-bottom))';document.documentElement.style.paddingBottom='0';qa('#map,.leaflet-container').forEach(function(m){m.style.touchAction='pan-x pan-y';m.style.zIndex='1'});qa('.leaflet-control-container,.leaflet-pane,.leaflet-top,.leaflet-bottom').forEach(function(x){x.style.zIndex='400'});qa('button,a,[role=button]').forEach(function(b){b.style.pointerEvents='auto'})}
(function style(){if(q('#fixedBottomStyle'))return;var s=document.createElement('style');s.id='fixedBottomStyle';s.textContent='html,body{min-height:100%;overscroll-behavior:none}body{padding-bottom:calc(110px + env(safe-area-inset-bottom))!important}.leaflet-container{z-index:1!important}.leaflet-control-container{z-index:400!important}#fixedAppBottomBar{position:fixed!important;left:10px!important;right:10px!important;bottom:calc(10px + env(safe-area-inset-bottom))!important;z-index:2147483000!important;pointer-events:auto!important;transform:none!important}';document.head.appendChild(s)})();
window.fixBottomBar=fix;
setTimeout(fix,300);setTimeout(fix,1200);setInterval(fix,2000);
window.addEventListener('resize',fix);
window.addEventListener('orientationchange',function(){setTimeout(fix,400)});
document.addEventListener('touchstart',function(){setTimeout(fix,50)},{passive:true});
})();