(function(){
if(window.__friendsOpenFix)return;window.__friendsOpenFix=1;
var API='https://bztigwfnenwosulhxrxo.supabase.co/rest/v1/';
var KEY='sb_publishable_P76ca2ta_N7PWpA_Wm6lTw__DEzK19l';
function q(id){return document.getElementById(id)}
function esc(s){return String(s||'').replace(/[&<>]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[c]})}
function prof(){try{return JSON.parse(localStorage.ca_profile||'{}')}catch(e){return {}}}
function dev(){var p=prof();return p.device_id||localStorage.ca_device_stable||localStorage.ca_device||''}
async function rpc(path,body){var r=await fetch(API+path,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json'},body:JSON.stringify(body||{})});var t=await r.text();var d=t?JSON.parse(t):null;if(!r.ok)throw Error((d&&d.message)||t||r.statusText);return d}
function css(){if(q('friendsOpenFixStyle'))return;var s=document.createElement('style');s.id='friendsOpenFixStyle';s.textContent='#friends{display:none;padding:10px 10px 28px;overflow-y:auto;-webkit-overflow-scrolling:touch}.friendsHead2{background:linear-gradient(135deg,#0ea5e9,#fb923c);color:white;border-radius:26px;padding:16px;margin-bottom:10px}.friendCard2{display:grid;grid-template-columns:58px 1fr auto;gap:10px;align-items:center;background:white;border:1px solid #e2e8f0;border-radius:24px;padding:11px;margin-bottom:9px;box-shadow:0 12px 32px rgba(15,23,42,.07)}.friendAv2{width:58px;height:58px;border-radius:50%;object-fit:cover;background:#e0f2fe;display:grid;place-items:center;color:#075985;font-weight:1000}.friendLoc2{font-size:13px;font-weight:1000;color:#0f766e}.friendLoc2.none{color:#94a3b8}.friendEmpty2{border:1px dashed #cbd5e1;background:#f8fafc;border-radius:22px;padding:18px;text-align:center;color:#64748b;font-weight:900}#realMobileNav{grid-template-columns:1fr 1fr 1fr 1fr!important}';document.head.appendChild(s)}
function av(p){if(p.photo_url)return '<img class="friendAv2" src="'+esc(p.photo_url)+'">';return '<div class="friendAv2">'+esc((p.display_name||p.username||'◇').slice(0,1).toUpperCase())+'</div>'}
function hideScreens(){['map','help','profile','venue'].forEach(function(id){var e=q(id);if(e)e.style.display='none'});var fr=q('friends');if(fr)fr.style.display='block'}
function setNav(){['rmnMap','rmnMsg','rmnFriends','rmnProfile'].forEach(function(id){var b=q(id);if(b)b.classList.remove('active')});var f=q('rmnFriends');if(f)f.classList.add('active')}
window.openFriends=function(){css();var fr=q('friends');if(!fr){fr=document.createElement('section');fr.id='friends';document.body.appendChild(fr)}hideScreens();setNav();window.renderFriendsFixed();if(window.fitScreensAboveNav)setTimeout(fitScreensAboveNav,80)}
window.renderFriendsFixed=async function(){css();var fr=q('friends');if(!fr)return;fr.innerHTML='<div class="friendsHead2"><h2 style="margin:0;font-size:27px">Arkadaşlar</h2><div style="font-weight:900;opacity:.9">Karşılıklı kabul ettiğin kişiler</div></div><div id="friendsList2"><div class="friendEmpty2">Arkadaşlar yükleniyor...</div></div>';try{var rows=await rpc('rpc/my_friends_v1',{p_device_id:dev()});var list=q('friendsList2');if(!rows||!rows.length){list.innerHTML='<div class="friendEmpty2">Henüz arkadaşın yok. Mesaj isteği kabul edilince burada gözükecek.</div>';return}list.innerHTML=rows.map(function(p){var loc=p.venue_name?'<div class="friendLoc2">📍 '+esc(p.venue_name)+' '+esc(p.area||'')+'</div>':'<div class="friendLoc2 none">Şu an hiçbir yerde değil</div>';return '<div class="friendCard2" data-user="'+esc(p.username||'')+'">'+av(p)+'<div><b>'+esc(p.display_name||p.username||'Kullanıcı')+'</b><br><small>@'+esc(p.username||'')+'</small>'+loc+'</div><button class="friendBtn">Profil</button></div>'}).join('');list.onclick=function(e){var c=e.target.closest('.friendCard2');if(c&&window.msgInvite)msgInvite(c.dataset.user)}}catch(e){q('friendsList2').innerHTML='<div class="friendEmpty2">Arkadaşlar gelmedi: '+esc(e.message)+'</div>'}}
function ensureButton(){css();var nav=q('realMobileNav');if(!nav)return;if(!q('rmnFriends')){var b=document.createElement('button');b.id='rmnFriends';b.textContent='Arkadaşlar';var profBtn=q('rmnProfile');nav.insertBefore(b,profBtn||null)}q('rmnFriends').onclick=function(e){e.preventDefault();e.stopPropagation();openFriends()}}
var oldShow=window.show;
window.show=function(id){if(id==='friends'){openFriends();return}if(oldShow)oldShow(id);var fr=q('friends');if(fr)fr.style.display='none';setTimeout(ensureButton,50)}
setTimeout(ensureButton,200);setTimeout(ensureButton,1000);setInterval(ensureButton,1200);
})();