(function(){
if(window.__friendsLocationPatch)return;window.__friendsLocationPatch=1;
var API='https://bztigwfnenwosulhxrxo.supabase.co/rest/v1/';
var KEY='sb_publishable_P76ca2ta_N7PWpA_Wm6lTw__DEzK19l';
function q(id){return document.getElementById(id)}
function esc(s){return String(s||'').replace(/[&<>]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[c]})}
function safe(s){return String(s||'').replace(/[,()]/g,'')}
function prof(){try{return JSON.parse(localStorage.ca_profile||'{}')}catch(e){return {}}}
function dev(){var p=prof();return p.device_id||localStorage.ca_device_stable||localStorage.ca_device||''}
async function rpc(path,body){var r=await fetch(API+path,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json'},body:JSON.stringify(body||{})});var t=await r.text();var d=t?JSON.parse(t):null;if(!r.ok)throw Error((d&&d.message)||t||r.statusText);return d}
function css(){if(q('friendsLocStyle'))return;var s=document.createElement('style');s.id='friendsLocStyle';s.textContent='.whereBar{position:relative;z-index:9999;margin:8px 10px;padding:10px 12px;border-radius:20px;background:rgba(255,255,255,.95);box-shadow:0 12px 28px rgba(2,132,199,.18);border:1px solid #bae6fd;color:#075985;font-weight:1000}.whereBar small{display:block;color:#64748b;font-weight:900}.friendsWrap{padding:10px 10px 28px}.friendsHead{background:linear-gradient(135deg,#0ea5e9,#fb923c);color:white;border-radius:26px;padding:16px;margin-bottom:10px;box-shadow:0 16px 38px rgba(2,132,199,.18)}.friendsTitle{font-size:27px;font-weight:1000;margin:0}.friendsSub{font-weight:900;opacity:.9}.friendList{display:grid;gap:9px}.friendCard{display:grid;grid-template-columns:58px 1fr auto;gap:10px;align-items:center;background:white;border:1px solid #e2e8f0;border-radius:24px;padding:11px;box-shadow:0 12px 32px rgba(15,23,42,.07)}.friendAv{width:58px;height:58px;border-radius:50%;object-fit:cover;background:linear-gradient(135deg,#e0f2fe,#dbeafe);display:grid;place-items:center;color:#075985;font-weight:1000;border:2px solid #bae6fd}.friendName{font-size:16px;font-weight:1000;color:#0f172a}.friendUser{font-size:12px;color:#64748b;font-weight:900}.friendLoc{font-size:13px;font-weight:1000;color:#0f766e;margin-top:4px}.friendLoc.none{color:#94a3b8}.friendBtn{border:0;border-radius:999px;padding:9px 10px;background:#e0f2fe;color:#075985;font-weight:1000}.friendEmpty{border:1px dashed #cbd5e1;background:#f8fafc;border-radius:22px;padding:18px;text-align:center;color:#64748b;font-weight:900}#realMobileNav{grid-template-columns:1fr 1fr 1fr 1fr!important}#realMobileNav button{font-size:12px!important;padding:11px 5px!important}';document.head.appendChild(s)}
function av(p){if(p&&p.photo_url)return '<img class="friendAv" src="'+esc(p.photo_url)+'">';return '<div class="friendAv">'+esc(((p&&p.display_name)||'◇').slice(0,1).toUpperCase())+'</div>'}
async function updateWhere(){css();var map=q('map');if(!map)return;var holder=q('whereBar');if(!holder){holder=document.createElement('div');holder.id='whereBar';holder.className='whereBar';map.parentNode.insertBefore(holder,map)}try{var d=dev();if(!d){holder.innerHTML='Şu an: <b>Profil yok</b><small>Konum göstermek için giriş yap.</small>';return}var x=await rpc('rpc/my_location_v1',{p_device_id:d});if(x&&x.status==='here')holder.innerHTML='Şu an: <b>'+esc(x.venue_name)+'</b><small>'+esc(x.area||'Çeşme')+'</small>';else holder.innerHTML='Şu an: <b>Hiçbir yerde değilsin</b><small>Bir mekâna tıklayıp Buradayım diyebilirsin.</small>'}catch(e){holder.innerHTML='Şu an: <b>Konum okunamadı</b>'}}
window.renderFriends=async function(){css();var host=q('friends');if(!host){host=document.createElement('section');host.id='friends';host.className='screen';document.body.appendChild(host)}host.innerHTML='<div class="friendsWrap"><div class="friendsHead"><h2 class="friendsTitle">Arkadaşlar</h2><div class="friendsSub">Karşılıklı mesaj isteği kabul edilen kişiler</div></div><div id="friendList" class="friendList"><div class="friendEmpty">Arkadaşlar yükleniyor...</div></div></div>';try{var rows=await rpc('rpc/my_friends_v1',{p_device_id:dev()});var list=q('friendList');if(!rows||!rows.length){list.innerHTML='<div class="friendEmpty">Henüz arkadaşın yok. Mesaj isteği kabul edilince burada gözükecek.</div>';return}list.innerHTML=rows.map(function(p){var loc=p.venue_name?'<div class="friendLoc">📍 '+esc(p.venue_name)+' <small>'+esc(p.area||'')+'</small></div>':'<div class="friendLoc none">Şu an hiçbir yerde değil</div>';return '<div class="friendCard" data-user="'+esc(p.username||'')+'">'+av(p)+'<div><div class="friendName">'+esc(p.display_name||p.username||'Kullanıcı')+'</div><div class="friendUser">@'+esc(p.username||'')+'</div>'+loc+'</div><button class="friendBtn">Profil</button></div>'}).join('');list.onclick=function(e){var c=e.target.closest('.friendCard');if(!c)return;if(window.msgInvite)c.dataset.user&&msgInvite(c.dataset.user)}}catch(e){q('friendList').innerHTML='<div class="friendEmpty">Arkadaşlar gelmedi: '+esc(e.message)+'</div>'}if(window.fitScreensAboveNav)setTimeout(fitScreensAboveNav,100)}
function addFriendsNav(){css();var nav=q('realMobileNav');if(!nav)return;if(q('rmnFriends'))return;var b=document.createElement('button');b.id='rmnFriends';b.textContent='Arkadaşlar';b.onclick=function(){if(window.show)show('friends');else renderFriends();setActiveFriend()};nav.insertBefore(b,q('rmnProfile')||null)}
function setActiveFriend(){['rmnMap','rmnMsg','rmnFriends','rmnProfile'].forEach(function(id){var b=q(id);if(b)b.classList.remove('active')});var f=q('rmnFriends');if(f)f.classList.add('active')}
var oldShow=window.show;window.show=function(id){if(oldShow)oldShow(id);if(id==='map')setTimeout(updateWhere,120);if(id==='friends'){['map','help','profile','venue'].forEach(function(x){var e=q(x);if(e)e.style.display='none'});var fr=q('friends');if(fr)fr.style.display='block';renderFriends();setActiveFriend()}else{var fr=q('friends');if(fr)fr.style.display='none'}setTimeout(addFriendsNav,80)}
var oldHere=window.popupHere||window.checkinAction;window.popupHere=async function(id){if(oldHere)await oldHere(id);setTimeout(updateWhere,250)}
var oldNot=window.popupNotHere||window.leaveVenue;window.popupNotHere=async function(id){if(oldNot)await oldNot(id);setTimeout(updateWhere,250)}
setTimeout(function(){addFriendsNav();updateWhere()},700);
setInterval(function(){if(q('whereBar'))updateWhere();if(q('friends')&&q('friends').style.display!=='none')renderFriends()},5000);
})();