(function(){
if(window.__venueSearchPatch)return;window.__venueSearchPatch=1;
var open=false;
function q(i){return document.getElementById(i)}
function esc(s){return String(s||'').replace(/[&<>]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[c]})}
function mapEl(){return q('map')}
function mapOn(){var m=mapEl();if(!m)return false;var st=getComputedStyle(m),r=m.getBoundingClientRect();return st.display!=='none'&&r.width>100&&r.height>100}
function css(){if(q('venueSearchStyle'))return;var s=document.createElement('style');s.id='venueSearchStyle';s.textContent='.vsWrap{position:absolute;left:10px;right:10px;bottom:18px;z-index:1200;display:none;flex-direction:column-reverse;align-items:flex-start;pointer-events:auto}.vsToggle{border:0;border-radius:999px;background:#0ea5e9;color:white;font-weight:1000;padding:11px 14px;box-shadow:0 12px 28px rgba(2,132,199,.24)}.vsBox{display:none;margin-bottom:8px;width:min(92vw,430px)}.vsBox.open{display:block}.vsInner{background:rgba(255,255,255,.97);border:1px solid #bae6fd;border-radius:22px;padding:8px;box-shadow:0 12px 30px rgba(2,132,199,.18)}.vsTop{display:grid;grid-template-columns:1fr auto;gap:7px}.vsInput{width:100%;box-sizing:border-box;border:1px solid #bae6fd;border-radius:999px;padding:11px 14px;font-weight:900;outline:0;background:white}.vsClose{border:0;border-radius:999px;background:#fee2e2;color:#991b1b;font-weight:1000;padding:0 12px}.vsList{margin-top:6px;max-height:220px;overflow:auto}.vsItem{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:9px;border-top:1px solid #e0f2fe;font-weight:900}.vsItem small{display:block;color:#64748b;font-weight:800}.vsGo{border:0;border-radius:999px;background:#fb923c;color:white;padding:8px 11px;font-weight:1000}.vsPick{border:0;border-radius:999px;background:#e0f2fe;color:#075985;padding:8px 11px;font-weight:1000}@media(max-width:760px){.vsWrap{left:8px;right:8px;bottom:22px}.vsBox{width:100%}.vsInput{padding:10px 12px;font-size:13px}.vsItem{font-size:13px;align-items:flex-start}.vsItem>div:last-child{display:grid;gap:5px}}';document.head.appendChild(s)}
function ensure(){css();var b=q('uapBtn');if(b)b.remove();var g=q('gcsBtn');if(g)g.remove();var m=mapEl();var wrap=q('venueSearchWrap');if(!wrap){wrap=document.createElement('div');wrap.id='venueSearchWrap';wrap.className='vsWrap';wrap.innerHTML='<button id="venueSearchToggle" class="vsToggle">🔍 Mekan ara</button><div id="venueSearchBox" class="vsBox"><div class="vsInner"><div class="vsTop"><input id="venueSearchInput" class="vsInput" placeholder="Starbucks, Mercan, Alaçatı..."><button id="venueSearchClose" class="vsClose">×</button></div><div id="venueSearchList" class="vsList"></div></div></div>';if(m){m.style.position='relative';m.appendChild(wrap)}else document.body.appendChild(wrap);q('venueSearchToggle').onclick=function(){open=true;toggle();setTimeout(function(){var i=q('venueSearchInput');if(i)i.focus()},50)};q('venueSearchClose').onclick=function(){open=false;toggle()};q('venueSearchInput').oninput=render}else if(m&&wrap.parentElement!==m){m.style.position='relative';m.appendChild(wrap)}wrap.style.display=mapOn()?'flex':'none';toggle()}
function toggle(){var box=q('venueSearchBox'),inp=q('venueSearchInput'),list=q('venueSearchList');if(box)box.className='vsBox '+(open?'open':'');if(!open){if(inp)inp.value='';if(list)list.innerHTML=''}}
function matches(t,v){t=t.toLowerCase();return String((v.name||'')+' '+(v.area||'')+' '+(v.category||'')).toLowerCase().includes(t)}
function render(){var inp=q('venueSearchInput'),list=q('venueSearchList');if(!inp||!list)return;var t=inp.value.trim();if(t.length<2){list.innerHTML='';return}var arr=(window.venues||[]).filter(function(v){return matches(t,v)}).slice(0,8);if(!arr.length){list.innerHTML='<div class="vsItem">Sonuç yok</div>';return}list.innerHTML=arr.map(function(v){return '<div class="vsItem"><div><b>'+esc(v.name)+'</b><small>'+esc(v.area||'')+' · '+esc(v.category||'Mekan')+' · '+Number(v.live_count||0)+' kişi</small></div><div><button class="vsPick" onclick="window.venueSearchFocus(\''+esc(v.id)+'\')">Göster</button><button class="vsGo" onclick="window.popupHere(\''+esc(v.id)+'\')">Buradayım</button></div></div>'}).join('')}
window.venueSearchFocus=function(id){var v=(window.venues||[]).find(function(x){return x.id===id});if(!v)return;if(window.map){window.map.setView([v.lat,v.lng],17)}if(window.popupDetail)window.popupDetail(id)}
var os=window.show;window.show=function(x){if(os)os(x);setTimeout(ensure,150);setTimeout(render,300)}
setTimeout(ensure,900);setInterval(ensure,1500);
})();