(function(){
if(window.__venueSearchPatch)return;window.__venueSearchPatch=1;
function q(i){return document.getElementById(i)}
function esc(s){return String(s||'').replace(/[&<>]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[c]})}
function mapOn(){var m=q('map');if(!m)return false;var st=getComputedStyle(m),r=m.getBoundingClientRect();return st.display!=='none'&&r.width>100&&r.height>100}
function css(){if(q('venueSearchStyle'))return;var s=document.createElement('style');s.id='venueSearchStyle';s.textContent='.vsBox{position:fixed;left:12px;right:12px;top:calc(58px + env(safe-area-inset-top));z-index:2147482500;display:none}.vsInner{background:rgba(255,255,255,.96);border:1px solid #bae6fd;border-radius:22px;padding:8px;box-shadow:0 12px 30px rgba(2,132,199,.18)}.vsInput{width:100%;box-sizing:border-box;border:1px solid #bae6fd;border-radius:999px;padding:12px 14px;font-weight:900;outline:0}.vsList{margin-top:6px;max-height:260px;overflow:auto}.vsItem{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:9px;border-top:1px solid #e0f2fe;font-weight:900}.vsItem small{display:block;color:#64748b;font-weight:800}.vsGo{border:0;border-radius:999px;background:#fb923c;color:white;padding:8px 11px;font-weight:1000}.vsPick{border:0;border-radius:999px;background:#e0f2fe;color:#075985;padding:8px 11px;font-weight:1000}@media(max-width:760px){.vsBox{top:calc(52px + env(safe-area-inset-top));left:10px;right:10px}.vsInput{padding:10px 12px;font-size:13px}.vsItem{font-size:13px}}';document.head.appendChild(s)}
function ensure(){css();var b=q('uapBtn');if(b)b.remove();var g=q('gcsBtn');if(g)g.remove();var box=q('venueSearchBox');if(!box){box=document.createElement('div');box.id='venueSearchBox';box.className='vsBox';box.innerHTML='<div class="vsInner"><input id="venueSearchInput" class="vsInput" placeholder="Mekan ara: Starbucks, Mercan, Alaçatı..."><div id="venueSearchList" class="vsList"></div></div>';document.body.appendChild(box);q('venueSearchInput').oninput=render}box.style.display=mapOn()?'block':'none'}
function matches(t,v){t=t.toLowerCase();return String((v.name||'')+' '+(v.area||'')+' '+(v.category||'')).toLowerCase().includes(t)}
function render(){var inp=q('venueSearchInput'),list=q('venueSearchList');if(!inp||!list)return;var t=inp.value.trim();if(t.length<2){list.innerHTML='';return}var arr=(window.venues||[]).filter(function(v){return matches(t,v)}).slice(0,8);if(!arr.length){list.innerHTML='<div class="vsItem">Sonuç yok</div>';return}list.innerHTML=arr.map(function(v){return '<div class="vsItem"><div><b>'+esc(v.name)+'</b><small>'+esc(v.area||'')+' · '+esc(v.category||'Mekan')+' · '+Number(v.live_count||0)+' kişi</small></div><div><button class="vsPick" onclick="window.venueSearchFocus(\''+esc(v.id)+'\')">Göster</button><button class="vsGo" onclick="window.popupHere(\''+esc(v.id)+'\')">Buradayım</button></div></div>'}).join('')}
window.venueSearchFocus=function(id){var v=(window.venues||[]).find(function(x){return x.id===id});if(!v)return;if(window.map){window.map.setView([v.lat,v.lng],17)}if(window.popupDetail)window.popupDetail(id)}
var os=window.show;window.show=function(x){if(os)os(x);setTimeout(ensure,150);setTimeout(render,300)}
setTimeout(ensure,900);setInterval(ensure,1500);
})();