(function(){
if(window.__profileChatHotfix)return;window.__profileChatHotfix=1;
var API=window.API||'https://bztigwfnenwosulhxrxo.supabase.co/rest/v1/';
var KEY=window.KEY||'sb_publishable_P76ca2ta_N7PWpA_Wm6lTw__DEzK19l';
function q(id){return document.getElementById(id)}
function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function clean(s){return String(s||'').toLowerCase().replace(/[^a-z0-9_]/g,'').slice(0,20)}
function list(s){return String(s||'').split(',').map(function(x){return x.trim()}).filter(Boolean)}
function textInterests(x){if(Array.isArray(x))return x.join(', ');return String(x||'').replace(/[{}]/g,'').split(',').map(function(v){return v.trim()}).filter(Boolean).join(', ')}
function getP(){try{return JSON.parse(localStorage.ca_profile||'{}')}catch(e){return {}}}
function setP(p){localStorage.ca_profile=JSON.stringify(p)}
function dev(){var p=getP();var d=p.device_id||localStorage.ca_device_stable||localStorage.ca_device;if(!d){d='dev_'+Math.random().toString(36).slice(2)+'_'+Date.now()}localStorage.ca_device_stable=d;localStorage.ca_device=d;return d}
window.dev=dev;
async function api(path,params,opt){var u=new URL(API+path);Object.keys(params||{}).forEach(function(k){u.searchParams.set(k,params[k])});var h={apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json',Prefer:'return=representation'};var r=await fetch(u,{method:(opt&&opt.method)||'GET',headers:h,body:opt&&opt.body?JSON.stringify(opt.body):undefined});var t=await r.text();var d=t?JSON.parse(t):null;if(!r.ok)throw Error((d&&d.message)||t||r.statusText);return d}
function saveSession(row,pin){var p={device_id:row.device_id,user:row.username,name:row.display_name,gender:row.gender||'',age:row.age||'',bio:row.bio||'',interests:textInterests(row.interests),photo:row.photo_url||'',pin:pin||getP().pin||''};setP(p);localStorage.ca_device_stable=row.device_id;localStorage.ca_device=row.device_id;return p}
function av(src,small){return src?'<img class="mvpAvatar '+(small?'sm':'')+'" src="'+esc(src)+'">':'<div class="mvpAvatar '+(small?'sm':'')+'">◇</div>'}
function css(){if(q('hotfixStyle'))return;var s=document.createElement('style');s.id='hotfixStyle';s.textContent='.hfTabs{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:10px}.hfTab{border:0;border-radius:18px;padding:12px;font-weight:1000;background:#e0f2fe;color:#075985}.hfTab.on{background:linear-gradient(135deg,#0ea5e9,#fb923c);color:white}.hfBox{background:white;border:1px solid #dbeafe;border-radius:26px;padding:14px;margin:10px 0;box-shadow:0 18px 44px #07598520}.hfPass{font-weight:900;letter-spacing:2px}.hfGeneral{background:linear-gradient(135deg,#082f49,#0ea5e9);color:white;border-radius:24px;padding:14px;margin:10px 0}.hfMsg{background:#f0f9ff;border:1px solid #bae6fd;border-radius:18px;padding:9px 11px;margin:8px 0}.hfMsg.me{background:#dcfce7;border-color:#bbf7d0}.hfRow{display:grid;grid-template-columns:1fr auto;gap:8px}.hfSmall{font-size:12px;color:#64748b;font-weight:800}.hfGeneral .hfSmall{color:#e0f2fe}';document.head.appendChild(s)}
window.renderProfile=function(mode){css();mode=mode||'login';var p=getP(),box=q('profile');if(!box)return;box.innerHTML='<h2>Profil</h2><div id="hfProfile"></div>';var html='<div class="hfTabs"><button class="hfTab '+(mode==='new'?'on':'')+'" onclick="renderProfile(\'new\')">Yeni profil oluştur</button><button class="hfTab '+(mode==='login'?'on':'')+'" onclick="renderProfile(\'login\')">Profilime gir</button></div>';
if(p.name&&p.user){var chips=textInterests(p.interests).split(',').map(function(x){return x.trim()}).filter(Boolean).map(function(x){return '<span class="mvpPill">'+esc(x)+'</span>'}).join('');html+='<div class="mvpHero"><div class="mvpTop">'+av(p.photo,false)+'<div><div class="mvpName">'+esc(p.name)+'</div><div class="mvpUser">@'+esc(p.user)+'</div></div></div><p>'+esc(p.bio||'Bio yok')+'</p><div>'+chips+'</div><div class="mvpStats"><div class="mvpStat">'+esc(p.gender||'?')+'<br><small>Cinsiyet</small></div><div class="mvpStat">'+esc(p.age||'?')+'<br><small>Yaş</small></div><div class="mvpStat">Aktif<br><small>Hesap</small></div></div></div><button class="btn light" onclick="hfLogout()">Çıkış yap / başka profile gir</button><button class="btn" onclick="renderProfile(\'edit\')">Profil bilgilerini düzenle</button>'}
if(mode==='new'){html+='<div class="hfBox"><b>Yeni profil oluştur</b><input id="hfNewUser" placeholder="benzersiz kullanıcı adı"><input id="hfNewPin" class="hfPass" type="password" placeholder="şifre / pin"><input id="hfNewName" placeholder="Adın"><select id="hfNewGender"><option value="">Cinsiyet</option><option>Erkek</option><option>Kadın</option></select><input id="hfNewAge" type="number" placeholder="Yaş"><textarea id="hfNewBio" rows="3" placeholder="Kısa bio"></textarea><input id="hfNewInterests" placeholder="İlgi alanları: spor, müzik, deniz"><button class="btn" onclick="hfCreateProfile()">Profili oluştur</button><div id="hfNewOut"></div></div>'}
if(mode==='login'){html+='<div class="hfBox"><b>Profilime gir</b><input id="hfLoginUser" placeholder="kullanıcı adı"><input id="hfLoginPin" class="hfPass" type="password" placeholder="şifre"><button class="btn" onclick="hfLoginProfile()">Profilime gir</button><div id="hfLoginOut" class="hfSmall">Kullanıcı adı + şifre ile aynı hesaba geri girersin.</div></div>'}
if(mode==='edit'&&p.name){html+='<div class="hfBox"><b>Profil bilgilerini düzenle</b><input id="hfEditName" value="'+esc(p.name||'')+'" placeholder="Adın"><select id="hfEditGender"><option value="">Cinsiyet</option><option '+(p.gender==='Erkek'?'selected':'')+'>Erkek</option><option '+(p.gender==='Kadın'?'selected':'')+'>Kadın</option></select><input id="hfEditAge" type="number" value="'+esc(p.age||'')+'" placeholder="Yaş"><textarea id="hfEditBio" rows="3" placeholder="Bio">'+esc(p.bio||'')+'</textarea><input id="hfEditInterests" value="'+esc(textInterests(p.interests))+'" placeholder="İlgi alanları"><button class="btn" onclick="hfUpdateProfile()">Kaydet</button><div id="hfEditOut"></div></div>'}
q('hfProfile').innerHTML=html};
window.hfLogout=function(){localStorage.removeItem('ca_profile');renderProfile('login')};
window.hfCreateProfile=async function(){var out=q('hfNewOut');var body={p_username:clean(q('hfNewUser').value),p_pin:q('hfNewPin').value,p_display_name:(q('hfNewName').value||'').trim(),p_age:parseInt(q('hfNewAge').value||0)||null,p_gender:q('hfNewGender').value,p_bio:q('hfNewBio').value||'',p_interests:q('hfNewInterests').value||'',p_photo_url:''};if(body.p_username.length<3){out.className='bad';out.innerHTML='Kullanıcı adı en az 3 karakter.';return}if(!body.p_pin||body.p_pin.length<4){out.className='bad';out.innerHTML='Şifre en az 4 karakter.';return}if(!body.p_display_name||!body.p_gender){out.className='bad';out.innerHTML='Ad ve cinsiyet zorunlu.';return}out.className='warn';out.innerHTML='Profil oluşturuluyor...';try{var row=await api('rpc/create_profile_with_pin',{}, {method:'POST',body:body});saveSession(row,body.p_pin);out.className='ok';out.innerHTML='Profil oluşturuldu.';renderProfile('login')}catch(e){out.className='bad';out.innerHTML=e.message.indexOf('alinmis')>-1?'Bu kullanıcı adı alınmış.':'Profil oluşturulamadı: '+esc(e.message)}};
window.hfLoginProfile=async function(){var out=q('hfLoginOut');var body={p_username:clean(q('hfLoginUser').value),p_pin:q('hfLoginPin').value};if(body.p_username.length<3||!body.p_pin){out.className='bad';out.innerHTML='Kullanıcı adı ve şifre gir.';return}out.className='warn';out.innerHTML='Giriş yapılıyor...';try{var row=await api('rpc/login_profile_with_pin',{}, {method:'POST',body:body});saveSession(row,body.p_pin);out.className='ok';out.innerHTML='Giriş başarılı.';renderProfile('login')}catch(e){out.className='bad';out.innerHTML='Giriş olmadı: '+esc(e.message)}};
window.hfUpdateProfile=async function(){var p=getP(),out=q('hfEditOut');if(!p.device_id){out.className='bad';out.innerHTML='Önce profilime gir.';return}var upd={display_name:(q('hfEditName').value||'').trim(),gender:q('hfEditGender').value,age:parseInt(q('hfEditAge').value||0)||null,bio:q('hfEditBio').value||'',interests:list(q('hfEditInterests').value),updated_at:new Date().toISOString(),last_seen:new Date().toISOString()};out.className='warn';out.innerHTML='Kaydediliyor...';try{var rows=await api('profiles',{device_id:'eq.'+encodeURIComponent(p.device_id)},{method:'PATCH',body:upd});p.name=upd.display_name;p.gender=upd.gender;p.age=upd.age||'';p.bio=upd.bio;p.interests=upd.interests.join(', ');setP(p);out.className='ok';out.innerHTML='Profil güncellendi.';renderProfile('login')}catch(e){out.className='bad';out.innerHTML='Kaydedilemedi: '+esc(e.message)}};
window.ensureProfile=async function(){var p=getP();if(!p.device_id||!p.user||!p.name){show('profile');alert('Önce Yeni profil oluştur veya Profilime gir.');throw Error('Profil yok')}return true};
async function generalLoad(){var box=q('hfGeneralMsgs');if(!box)return;try{var rows=await api('chat_room_messages',{room_id:'eq.general',select:'*',order:'created_at.asc',limit:'50'});box.innerHTML=rows.length?rows.map(function(m){return '<div class="hfMsg '+(m.sender_device===dev()?'me':'')+'"><b>'+esc(m.sender_name)+'</b><br>'+esc(m.body)+'</div>'}).join(''):'<div class="warn">Genel chatte ilk mesajı sen yaz.</div>';box.scrollTop=box.scrollHeight}catch(e){box.innerHTML='<div class="bad">Genel chat yüklenmedi: '+esc(e.message)+'</div>'}}
window.hfGeneralSend=async function(){try{await ensureProfile();var t=q('hfGeneralText'),body=(t.value||'').trim();if(!body)return;await api('chat_room_messages',{}, {method:'POST',body:{room_id:'general',sender_name:getP().name,sender_device:dev(),body:body.slice(0,800)}});t.value='';await generalLoad()}catch(e){alert('Mesaj gitmedi: '+e.message)}};
var oldRender=window.renderMsg;
window.renderMsg=async function(){css();if(oldRender)await oldRender();var host=q('help');if(!host)return;var target=q('hfGeneralWrap');if(!target){host.insertAdjacentHTML('afterbegin','<div id="hfGeneralWrap" class="hfGeneral"><h3>Genel Chat</h3><div class="hfSmall">Herkesin görebildiği ortak sohbet.</div><div id="hfGeneralMsgs" style="max-height:220px;overflow:auto;margin-top:8px"></div><div class="hfRow"><textarea id="hfGeneralText" rows="2" placeholder="Genel chate yaz..."></textarea><button class="btn warm" onclick="hfGeneralSend()">Gönder</button></div></div>')}await generalLoad()};
var oldShow=window.show;window.show=function(id){oldShow(id);if(id==='profile')setTimeout(function(){renderProfile('login')},0);if(id==='help')setTimeout(function(){if(window.renderMsg)window.renderMsg()},0)};
css();if(q('profile'))renderProfile('login');
})();