(function(){
if(window.__igMessagesUI)return;window.__igMessagesUI=1;
var API='https://bztigwfnenwosulhxrxo.supabase.co/rest/v1/';
var KEY='sb_publishable_P76ca2ta_N7PWpA_Wm6lTw__DEzK19l';
function el(id){return document.getElementById(id)}
function esc(s){return String(s||'').replace(/[&<>]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[c]})}
function safe(s){return String(s||'').replace(/[,()]/g,'')}
function clean(s){return String(s||'').toLowerCase().replace(/[^a-z0-9_]/g,'').slice(0,20)}
function me(){try{return JSON.parse(localStorage.ca_profile||'{}')}catch(e){return {}}}
function did(){var p=me();return p.device_id||localStorage.ca_device_stable||localStorage.ca_device||''}
async function api(path,params,opt){var u=new URL(API+path);Object.keys(params||{}).forEach(function(k){u.searchParams.set(k,params[k])});var r=await fetch(u,{method:(opt&&opt.method)||'GET',headers:{apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json',Prefer:'return=representation'},body:opt&&opt.body?JSON.stringify(opt.body):undefined});var t=await r.text();var d=t?JSON.parse(t):null;if(!r.ok)throw Error((d&&d.message)||t||r.statusText);return d}
function css(){if(el('igStyle'))return;var s=document.createElement('style');s.id='igStyle';s.textContent='.igWrap{padding:10px 10px 28px}.igHead{position:sticky;top:0;z-index:50;background:rgba(248,250,252,.94);backdrop-filter:blur(14px);padding:10px 0}.igTitle{font-size:28px;font-weight:1000;margin:0 0 10px;color:#0f172a}.igSearchRow{display:grid;grid-template-columns:1fr auto;gap:8px}.igSearch{width:100%;border:1px solid #dbeafe;border-radius:999px;background:white;padding:12px 14px;font-weight:900;outline:0}.igReq{border:0;border-radius:999px;background:#0ea5e9;color:white;font-weight:1000;padding:12px 14px}.igReq.hot{background:#fb923c}.igDrop{display:none;margin-top:10px;background:white;border:1px solid #e0f2fe;border-radius:22px;padding:10px;box-shadow:0 14px 35px rgba(2,132,199,.12)}.igDrop.on{display:block}.igList{display:grid;gap:8px}.igThread,.igUser,.igInv{display:grid;grid-template-columns:56px 1fr auto;gap:10px;align-items:center;background:white;border:1px solid #e2e8f0;border-radius:22px;padding:10px;box-shadow:0 10px 28px rgba(15,23,42,.06)}.igAv{width:56px;height:56px;border-radius:50%;background:linear-gradient(135deg,#e0f2fe,#dbeafe);display:grid;place-items:center;color:#075985;font-weight:1000;border:2px solid #bae6fd;object-fit:cover}.igName{font-size:16px;font-weight:1000;color:#0f172a}.igSub{font-size:13px;color:#64748b;max-width:170px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.igTime{font-size:11px;color:#94a3b8;font-weight:900}.igBtn{border:0;border-radius:999px;padding:8px 10px;font-weight:1000;background:#e0f2fe;color:#075985}.igOk{background:#22c55e;color:white}.igNo{background:#fee2e2;color:#991b1b}.igEmpty{text-align:center;border:1px dashed #cbd5e1;background:#f8fafc;border-radius:20px;padding:16px;color:#64748b;font-weight:800}.igSec{font-size:13px;color:#64748b;font-weight:1000;margin:14px 2px 8px}.igGen{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;background:linear-gradient(135deg,#0f172a,#0ea5e9);color:white;border-radius:24px;padding:14px;margin:10px 0}.igGen button{border:0;border-radius:999px;background:white;color:#075985;font-weight:1000;padding:10px 12px}';document.head.appendChild(s)}
function avatar(p){if(p&&p.photo_url)return '<img class="igAv" src="'+esc(p.photo_url)+'">';return '<div class="igAv">'+esc(((p&&p.display_name)||'◇').slice(0,1).toUpperCase())+'</div>'}
function ago(s){if(!s)return '';var d=(Date.now()-new Date(s).getTime())/1000;if(d<60)return 'simdi';if(d<3600)return Math.floor(d/60)+' dk';if(d<86400)return Math.floor(d/3600)+' sa';return Math.floor(d/86400)+' g'}
async function profs(ids){ids=[...new Set(ids.filter(Boolean))];if(!ids.length)return {};var rows=await api('profiles',{device_id:'in.('+ids.map(safe).join(',')+')',select:'device_id,username,display_name,photo_url'});var m={};rows.forEach(function(p){m[p.device_id]=p});return m}
async function lastMsgs(ids){var m={};if(!ids.length)return m;var rows=await api('direct_messages',{room_id:'in.('+ids.map(safe).join(',')+')',select:'room_id,body,created_at,sender_device',order:'created_at.desc',limit:'200'});rows.forEach(function(x){if(!m[x.room_id])m[x.room_id]=x});return m}
async function searchUsers(){var box=el('igSearchResults'),inp=el('igSearch');if(!box||!inp)return;var v=clean(inp.value);if(v.length<2){box.classList.remove('on');box.innerHTML='';return}box.classList.add('on');box.innerHTML='<div class="igEmpty">Araniyor...</div>';try{var rows=await api('rpc/find_profiles_by_username',{}, {method:'POST',body:{p_query:v,p_my_device:did()}});box.innerHTML=rows.length?rows.map(function(p){return '<div class="igUser" data-user="'+esc(p.username)+'">'+avatar(p)+'<div><div class="igName">'+esc(p.display_name||p.username)+'</div><div class="igSub">@'+esc(p.username)+'</div></div><button class="igBtn sendReq">Istek at</button></div>'}).join(''):'<div class="igEmpty">Kullanici yok.</div>'}catch(e){box.innerHTML='<div class="igEmpty">Arama olmadi.</div>'}}
async function loadInvites(show){var box=el('igInvites');if(!box)return;try{var rows=await api('chat_invitations',{to_device:'eq.'+did(),status:'eq.pending',select:'*',order:'created_at.desc'});var pp=await profs(rows.map(function(r){return r.from_device}));var b=el('igReqBtn');if(b){b.textContent='Istekler '+(rows.length?'('+rows.length+')':'');b.classList.toggle('hot',rows.length>0)}box.innerHTML=rows.length?rows.map(function(r){var p=pp[r.from_device]||{};return '<div class="igInv" data-id="'+esc(r.id)+'" data-user="'+esc(p.username||'chat')+'">'+avatar(p)+'<div><div class="igName">'+esc(p.display_name||p.username||'Kullanici')+'</div><div class="igSub">@'+esc(p.username||'')+' mesaj istegi</div></div><div style="display:grid;gap:6px"><button class="igBtn igOk acceptReq">Kabul</button><button class="igBtn igNo rejectReq">Sil</button></div></div>'}).join(''):'<div class="igEmpty">Yeni istek yok.</div>';if(show)box.classList.add('on')}catch(e){box.innerHTML='<div class="igEmpty">Istekler gelmedi.</div>'}}
async function loadInbox(){var box=el('igInbox');if(!box)return;box.innerHTML='<div class="igEmpty">Yukleniyor...</div>';try{var d=did();var rooms=await api('direct_rooms',{or:'(device_a.eq.'+safe(d)+',device_b.eq.'+safe(d)+')',select:'*',order:'created_at.desc'});var seen={};rooms=rooms.filter(function(r){var o=r.device_a===d?r.device_b:r.device_a;if(seen[o])return false;seen[o]=true;return true});var pp=await profs(rooms.map(function(r){return r.device_a===d?r.device_b:r.device_a}));var lm=await lastMsgs(rooms.map(function(r){return r.id}));if(!rooms.length){box.innerHTML='<div class="igEmpty">Henuz mesaj kutun yok. Yukaridan kullanici ara.</div>';return}box.innerHTML=rooms.map(function(r){var o=r.device_a===d?r.device_b:r.device_a,p=pp[o]||{},m=lm[r.id]||{},sub=m.body?((m.sender_device===d?'Sen: ':'')+m.body):'Henuz mesaj yok';return '<div class="igThread" data-room="'+esc(r.id)+'" data-user="'+esc(p.username||'chat')+'">'+avatar(p)+'<div><div class="igName">'+esc(p.display_name||p.username||'Kullanici')+'</div><div class="igSub">'+esc(sub)+'</div></div><div class="igTime">'+esc(ago(m.created_at||r.created_at))+'</div></div>'}).join('')}catch(e){box.innerHTML='<div class="igEmpty">Kutular gelmedi.</div>'}}
async function render(){css();var host=el('help')||document.body;host.innerHTML='<div class="igWrap"><div class="igHead"><h2 class="igTitle">Mesajlar</h2><div class="igSearchRow"><input id="igSearch" class="igSearch" placeholder="Kullanici ara..."><button id="igReqBtn" class="igReq">Istekler</button></div><div id="igSearchResults" class="igDrop"></div><div id="igInvites" class="igDrop"></div></div><div class="igGen"><div><b>Genel Chat</b><br><small>Herkesin ortak sohbeti</small></div><button id="igGenBtn">Ac</button></div><div id="igGenBox" style="display:none"><div id="hfGeneralMsgs" class="cmfMsgs"></div><div class="cmfInput"><textarea id="hfGeneralText" rows="2" placeholder="Genel chate yaz..."></textarea><button class="btn" id="igGenSend">Gonder</button></div></div><div class="igSec">Sohbetler</div><div id="igInbox" class="igList"></div><div id="msgChatBox"></div></div>';el('igSearch').addEventListener('input',searchUsers);el('igReqBtn').onclick=function(){var b=el('igInvites');b.classList.toggle('on');if(b.classList.contains('on'))loadInvites(true)};el('igGenBtn').onclick=function(){var b=el('igGenBox');b.style.display=b.style.display==='none'?'block':'none';if(window.finalLoadGeneral)finalLoadGeneral()};el('igGenSend').onclick=function(){if(window.hfGeneralSend)hfGeneralSend()};host.onclick=function(e){var th=e.target.closest('.igThread');if(th&&window.cmfOpenChat)cmfOpenChat(th.dataset.room,th.dataset.user);var u=e.target.closest('.igUser');if(u&&e.target.classList.contains('sendReq')&&window.msgInvite)msgInvite(u.dataset.user);var inv=e.target.closest('.igInv');if(inv&&e.target.classList.contains('acceptReq')&&window.msgAccept)msgAccept(inv.dataset.id,inv.dataset.user);if(inv&&e.target.classList.contains('rejectReq')&&window.msgReject)msgReject(inv.dataset.id)};await loadInvites(false);await loadInbox();if(window.fitScreensAboveNav)setTimeout(fitScreensAboveNav,80)}
window.renderMsg=render;window.loadChats=loadInbox;window.igLoadInbox=loadInbox;window.igLoadInvites=loadInvites;
var oldShow=window.show;window.show=function(id){if(oldShow)oldShow(id);if(id==='help')setTimeout(render,60)}
setInterval(function(){if(el('igInbox'))loadInbox();if(el('igInvites'))loadInvites(false)},3500);
})();