(function(){
if(window.__leaveDeletePatch)return;window.__leaveDeletePatch=1;
var API='https://bztigwfnenwosulhxrxo.supabase.co/rest/v1/';
var KEY='sb_publishable_P76ca2ta_N7PWpA_Wm6lTw__DEzK19l';
function q(id){return document.getElementById(id)}
function esc(s){return String(s||'').replace(/[&<>]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[c]})}
function prof(){try{return JSON.parse(localStorage.ca_profile||'{}')}catch(e){return {}}}
function dev(){var p=prof();return p.device_id||localStorage.ca_device_stable||localStorage.ca_device||''}
async function api(path,params,opt){var u=new URL(API+path);Object.keys(params||{}).forEach(function(k){u.searchParams.set(k,params[k])});var r=await fetch(u,{method:(opt&&opt.method)||'GET',headers:{apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json',Prefer:'return=representation'},body:opt&&opt.body?JSON.stringify(opt.body):undefined});var t=await r.text();var d=t?JSON.parse(t):null;if(!r.ok)throw Error((d&&d.message)||t||r.statusText);return d}
function css(){if(q('leaveDeleteStyle'))return;var s=document.createElement('style');s.id='leaveDeleteStyle';s.textContent='.delBtn,.leaveBtn{border:0;border-radius:999px;padding:7px 10px;font-weight:950;margin-top:6px}.delBtn{background:#fee2e2;color:#991b1b}.leaveBtn{background:#f1f5f9;color:#0f172a;border:1px solid #cbd5e1}.noneHere{background:#f8fafc;border:1px dashed #94a3b8;color:#334155;border-radius:18px;padding:10px;margin:8px 0}.cmfMsg .delBtn,.hfMsg .delBtn{font-size:11px;padding:5px 8px}.venueLeaveBar{display:grid;grid-template-columns:1fr;gap:8px;margin:8px 0}';document.head.appendChild(s)}
async function rpc(path,body){return api(path,{}, {method:'POST',body:body})}
window.leaveVenue=async function(){try{var d=dev();if(!d){if(window.show)show('profile');alert('Once profile gir.');return}await rpc('rpc/leave_venue_v1',{p_device_id:d});window.selected=null;if(q('venueInfo'))q('venueInfo').innerHTML='<div class="noneHere">Artik hicbir yerde gorunmuyorsun.</div>';if(q('peopleList'))q('peopleList').innerHTML='';if(window.loadVenues)await loadVenues();alert('Artik burada degilsin. Hicbir yer secili degil.')}catch(e){alert('Konum kaldirilamadi: '+e.message)}};
function addLeaveButton(){css();var vi=q('venueInfo');if(vi&&!q('leaveVenueBtn'))vi.insertAdjacentHTML('afterbegin','<div class="venueLeaveBar"><button id="leaveVenueBtn" class="leaveBtn" onclick="leaveVenue()">Artik burada degilim</button></div>')}
var oldSelect=window.selectVenue;window.selectVenue=function(id){if(oldSelect)oldSelect(id);setTimeout(addLeaveButton,50)};
var oldCheck=window.checkInSelected;window.checkInSelected=async function(){if(oldCheck)await oldCheck();setTimeout(addLeaveButton,80)};
var oldQuick=window.quickCheckIn;window.quickCheckIn=async function(id){if(oldQuick)await oldQuick(id);setTimeout(addLeaveButton,80)};
var oldCmf=window.cmfCheckin;window.cmfCheckin=async function(id){if(oldCmf)await oldCmf(id);setTimeout(addLeaveButton,80)};
var oldDo=window.doCheckin;window.doCheckin=async function(id){if(oldDo)await oldDo(id);setTimeout(addLeaveButton,80)};
window.delPrivateMsg=async function(id,room,u){try{await rpc('rpc/delete_direct_message_v1',{p_message_id:id,p_device_id:dev()});if(window.cmfOpenChat)await cmfOpenChat(room,u||'chat')}catch(e){alert('Mesaj silinemedi: '+e.message)}};
window.delGeneralMsg=async function(id){try{await rpc('rpc/delete_general_message_v1',{p_message_id:id,p_device_id:dev()});if(window.finalLoadGeneral)await finalLoadGeneral();else if(window.renderMsg)await renderMsg()}catch(e){alert('Mesaj silinemedi: '+e.message)}};
async function loadMsgs(room,u){var box=q('cmfMsgs');if(!box)return;try{var rows=await api('direct_messages',{room_id:'eq.'+room,select:'*',order:'created_at.asc'});box.innerHTML=rows.length?rows.map(function(m){var me=m.sender_device===dev();var del=me?'<br><button class="delBtn" onclick="delPrivateMsg(\''+esc(m.id)+'\',\''+esc(room)+'\',\''+esc(u||'chat')+'\')">Sil</button>':'';return '<div class="cmfMsg '+(me?'me':'')+'"><b>'+esc(m.sender_name)+'</b><br>'+esc(m.body)+del+'</div>'}).join(''):'<div class="warn">Ilk mesaji yaz.</div>';box.scrollTop=box.scrollHeight}catch(e){box.innerHTML='<div class="bad">Mesajlar gelmedi: '+esc(e.message)+'</div>'}}
window.cmfOpenChat=async function(room,u){var box=q('msgChatBox');if(!box)return;box.style.display='block';box.innerHTML='<div class="cmfPanel"><b>@'+esc(u||'chat')+'</b><br><span>Ozel sohbet</span></div><div id="cmfMsgs" class="cmfMsgs">Yukleniyor...</div><div class="cmfInput"><textarea id="cmfText" rows="2" placeholder="Mesaj yaz..."></textarea><button class="btn" onclick="cmfSend(\''+esc(room)+'\',\''+esc(u||'chat')+'\')">Gonder</button></div>';await loadMsgs(room,u)};
window.cmfSend=async function(room,u){try{var t=q('cmfText'),body=(t.value||'').trim();if(!body)return;await api('direct_messages',{}, {method:'POST',body:{room_id:room,sender_device:dev(),sender_name:prof().name,body:body.slice(0,800)}});t.value='';await loadMsgs(room,u)}catch(e){alert('Mesaj gitmedi: '+e.message)}};
window.finalLoadGeneral=async function(){var box=q('hfGeneralMsgs');if(!box)return;try{var rows=await api('chat_room_messages',{room_id:'eq.general',select:'*',order:'created_at.asc',limit:'70'});box.innerHTML=rows.length?rows.map(function(m){var me=m.sender_device===dev();var del=me?'<br><button class="delBtn" onclick="delGeneralMsg(\''+esc(m.id)+'\')">Sil</button>':'';return '<div class="hfMsg '+(me?'me':'')+'"><b>'+esc(m.sender_name)+'</b><br>'+esc(m.body)+del+'</div>'}).join(''):'<div class="warn">Genel chatte ilk mesaji sen yaz.</div>';box.scrollTop=box.scrollHeight}catch(e){}};
var oldRender=window.renderMsg;window.renderMsg=async function(){if(oldRender)await oldRender();if(window.finalLoadGeneral)await finalLoadGeneral();setTimeout(addLeaveButton,50)};
css();setTimeout(addLeaveButton,1000);
})();