(function(){
if(window.__mapOnlyBrandLocation)return;window.__mapOnlyBrandLocation=1;
var API='https://bztigwfnenwosulhxrxo.supabase.co/rest/v1/';
var KEY='sb_publishable_P76ca2ta_N7PWpA_Wm6lTw__DEzK19l';
function q(s){return document.querySelector(s)}
function qa(s){return Array.prototype.slice.call(document.querySelectorAll(s))}
function esc(s){return String(s||'').replace(/[&<>]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[c]})}
function prof(){try{return JSON.parse(localStorage.ca_profile||'{}')}catch(e){return {}}}
function dev(){var p=prof();return p.device_id||localStorage.ca_device_stable||localStorage.ca_device||''}
async function rpc(path,body){var r=await fetch(API+path,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json'},body:JSON.stringify(body||{})});var t=await r.text();var d=t?JSON.parse(t):null;if(!r.ok)throw Error((d&&d.message)||t||r.statusText);return d}
function isMapVisible(){var m=document.getElementById('map');if(!m)return false;var r=m.getBoundingClientRect();return r.width>100&&r.height>100&&getComputedStyle(m).display!=='none'&&getComputedStyle(m).visibility!=='hidden'}
function hideOldHeader(){qa('header,.header,.top,.topbar,.brand,.hero,body *').forEach(function(el){if(el.id==='mapBrandLoc'||el.closest&&el.closest('#mapBrandLoc'))return;var t=(el.innerText||'').toLowerCase();var r=el.getBoundingClientRect();if(t.indexOf('çeşmeaşk')>-1&&(t.indexOf('mekanı seç')>-1||t.indexOf('görün')>-1||t.indexOf('tanış')>-1)&&r.top<180&&r.height<130){el.style.setProperty('display','none','important');el.style.setProperty('visibility','hidden','important');el.style.setProperty('height','0','important');el.style.setProperty('min-height','0','important');el.style.setProperty('padding','0','important');el.style.setProperty('margin','0','important')}})}
function make(){var o=document.getElementById('mapBrandLoc');if(!o){o=document.createElement('div');o.id='mapBrandLoc';o.innerHTML='<div class="mblBrand">ÇeşmeAşk</div><div id="mblWhere" class="mblWhere">Şu an: yükleniyor</div>';document.body.appendChild(o)}return o}
async function updateWhere(){var w=document.getElementById('mblWhere');if(!w)return;try{var d=dev();if(!d){w.innerHTML='Şu an: <b>Profil yok</b>';return}var x=await rpc('rpc/my_location_v1',{p_device_id:d});if(x&&x.status==='here')w.innerHTML='Şu an: <b>'+esc(x.venue_name)+'</b>';else w.innerHTML='Şu an: <b>Hiçbir yerde değilsin</b>'}catch(e){w.innerHTML='Şu an: <b>okunamadı</b>'}}
function apply(){hideOldHeader();var old=document.getElementById('whereBar');if(old){old.style.setProperty('display','none','important');old.style.setProperty('visibility','hidden','important')}
var o=make();if(isMapVisible()){o.style.setProperty('display','flex','important');updateWhere()}else{o.style.setProperty('display','none','important')}}
(function style(){if(q('#mapBrandLocStyle'))return;var s=document.createElement('style');s.id='mapBrandLocStyle';s.textContent='#mapBrandLoc{position:fixed!important;top:calc(12px + env(safe-area-inset-top))!important;left:14px!important;z-index:2147483600!important;display:flex!important;align-items:center!important;gap:10px!important;pointer-events:none!important}.mblBrand{font-family:Trebuchet MS,Avenir Next,system-ui,sans-serif!important;font-size:28px!important;line-height:1!important;font-weight:1000!important;letter-spacing:-.8px!important;color:#075985!important;text-shadow:0 3px 14px rgba(255,255,255,.95)!important;background:rgba(255,255,255,.84)!important;border:1px solid #bae6fd!important;border-radius:20px!important;padding:9px 13px!important;box-shadow:0 12px 28px rgba(2,132,199,.16)!important}.mblWhere{font-size:13px!important;font-weight:1000!important;color:#075985!important;background:rgba(255,255,255,.88)!important;border:1px solid #bae6fd!important;border-radius:999px!important;padding:9px 12px!important;box-shadow:0 12px 28px rgba(2,132,199,.14)!important;max-width:340px!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}#whereBar{display:none!important;visibility:hidden!important}@media(max-width:760px){#mapBrandLoc{left:10px!important;right:120px!important;gap:6px!important}.mblBrand{font-size:21px!important;padding:8px 10px!important}.mblWhere{font-size:11px!important;padding:8px 9px!important;min-width:0!important;max-width:calc(100vw - 250px)!important}}';document.head.appendChild(s)})();
var oldShow=window.show;window.show=function(id){if(oldShow)oldShow(id);setTimeout(apply,80);setTimeout(apply,300)}
var oldHere=window.popupHere||window.checkinAction;window.popupHere=async function(id){if(oldHere)await oldHere(id);setTimeout(updateWhere,200);setTimeout(apply,250)}
var oldNot=window.popupNotHere||window.leaveVenue;window.popupNotHere=async function(id){if(oldNot)await oldNot(id);setTimeout(updateWhere,200);setTimeout(apply,250)}
setTimeout(apply,150);setTimeout(apply,800);setTimeout(apply,1800);setInterval(apply,1500);
})();