(function(){
if(window.__mapOnlyBrandLocation)return;window.__mapOnlyBrandLocation=1;
var API='https://bztigwfnenwosulhxrxo.supabase.co/rest/v1/';
var KEY='sb_publishable_P76ca2ta_N7PWpA_Wm6lTw__DEzK19l';
var CITY={cesme:'Çeşme',izmir:'İzmir',istanbul:'İstanbul',ankara:'Ankara'};
function q(s){return document.querySelector(s)}
function qa(s){return Array.prototype.slice.call(document.querySelectorAll(s))}
function esc(s){return String(s||'').replace(/[&<>]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[c]})}
function prof(){try{return JSON.parse(localStorage.ca_profile||'{}')}catch(e){return {}}}
function dev(){var p=prof();return p.device_id||localStorage.ca_device_stable||localStorage.ca_device||''}
function curCity(){return localStorage.piyasa_city||'cesme'}
async function rpc(path,body){var r=await fetch(API+path,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json'},body:JSON.stringify(body||{})});var t=await r.text();var d=t?JSON.parse(t):null;if(!r.ok)throw Error((d&&d.message)||t||r.statusText);return d}
function isShown(id){var e=document.getElementById(id);if(!e)return false;var s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>20&&r.height>20}
function mapMode(){return isShown('map')&&!isShown('help')&&!isShown('friends')&&!isShown('profile')&&!isShown('venue')}
function hideOldHeader(){['whereBar','citySwitch'].forEach(function(id){var e=document.getElementById(id);if(e){e.style.setProperty('display','none','important');e.style.setProperty('visibility','hidden','important')}});qa('header,.header,.top,.topbar,.brand,.hero,body *').forEach(function(el){if(el.id==='mapBrandLoc'||el.closest&&el.closest('#mapBrandLoc'))return;var t=(el.innerText||'').toLowerCase();var r=el.getBoundingClientRect();if(r.top<180&&r.height<140&&(t.indexOf('mekanı seç')>-1||t.indexOf('mekânı seç')>-1||t.indexOf('görün')>-1||t.indexOf('tanış')>-1||t.indexOf('çeşmeaşk')>-1)){el.style.setProperty('display','none','important');el.style.setProperty('visibility','hidden','important');el.style.setProperty('height','0','important');el.style.setProperty('min-height','0','important');el.style.setProperty('padding','0','important');el.style.setProperty('margin','0','important');el.style.setProperty('overflow','hidden','important')}})}
function make(){var o=document.getElementById('mapBrandLoc');if(!o){o=document.createElement('div');o.id='mapBrandLoc';o.innerHTML='<div class="mblBrand">Piyasa</div><div id="mblWhere" class="mblWhere">Şu an: yükleniyor</div><div class="mblCity"><button id="mblCityBtn">Şehir</button><div id="mblMenu" class="mblMenu"><button data-city="cesme">Çeşme</button><button data-city="izmir">İzmir</button><button data-city="istanbul">İstanbul</button><button data-city="ankara">Ankara</button></div></div>';document.body.appendChild(o);document.getElementById('mblCityBtn').onclick=function(e){e.preventDefault();e.stopPropagation();document.getElementById('mblMenu').classList.toggle('on')};document.getElementById('mblMenu').onclick=function(e){var b=e.target.closest('button[data-city]');if(!b)return;localStorage.piyasa_city=b.dataset.city;document.getElementById('mblMenu').classList.remove('on');updateCity();if(window.loadVenues)loadVenues();if(window.show)show('map')};document.addEventListener('click',function(e){var m=document.getElementById('mblMenu');if(m&&!o.contains(e.target))m.classList.remove('on')})}return o}
function updateCity(){var b=document.getElementById('mblCityBtn');if(b)b.textContent=CITY[curCity()]||'Şehir'}
async function updateWhere(){var w=document.getElementById('mblWhere');if(!w)return;try{var d=dev();if(!d){w.innerHTML='Şu an: <b>Konum yok</b>';return}var x=await rpc('rpc/my_location_v1',{p_device_id:d});if(x&&x.status==='here')w.innerHTML='Şu an: <b>'+esc(x.venue_name)+'</b>';else w.innerHTML='Şu an: <b>Hiçbir yerde değilsin</b>'}catch(e){w.innerHTML='Şu an: <b>okunamadı</b>'}}
function apply(){hideOldHeader();var o=make();if(mapMode()){o.style.setProperty('display','grid','important');updateCity();updateWhere()}else{o.style.setProperty('display','none','important')}}
(function style(){if(q('#mapBrandLocStyle'))return;var s=document.createElement('style');s.id='mapBrandLocStyle';s.textContent='#mapBrandLoc{position:fixed!important;top:calc(10px + env(safe-area-inset-top))!important;left:14px!important;right:14px!important;z-index:2147483600!important;display:none;grid-template-columns:auto 1fr auto!important;align-items:center!important;gap:10px!important;background:rgba(255,255,255,.95)!important;border:1px solid #dbeafe!important;border-radius:24px!important;padding:10px 145px 10px 12px!important;box-shadow:0 14px 34px rgba(2,132,199,.16)!important;backdrop-filter:blur(18px)!important}.mblBrand{font-family:Trebuchet MS,Avenir Next,system-ui,sans-serif!important;font-size:30px!important;line-height:1!important;font-weight:1000!important;letter-spacing:-1px!important;color:#075985!important;white-space:nowrap!important}.mblWhere{min-width:0!important;font-size:14px!important;font-weight:900!important;color:#0f172a!important;background:#f0f9ff!important;border:1px solid #bae6fd!important;border-radius:999px!important;padding:9px 12px!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}.mblCity{position:relative!important}.mblCity button{border:0;border-radius:999px;background:#0ea5e9;color:white;font-weight:1000;padding:10px 14px;white-space:nowrap}.mblMenu{display:none;position:absolute;top:calc(100% + 8px);right:0;min-width:150px;background:white;border:1px solid #dbeafe;border-radius:18px;box-shadow:0 16px 36px rgba(2,132,199,.18);padding:8px}.mblMenu.on{display:grid;gap:6px}.mblMenu button{background:#f0f9ff;color:#075985;border-radius:12px;text-align:left;padding:10px 12px}#whereBar,#citySwitch{display:none!important;visibility:hidden!important}@media(max-width:760px){#mapBrandLoc{left:10px!important;right:10px!important;gap:6px!important;padding:8px 104px 8px 10px!important}.mblBrand{font-size:22px!important}.mblWhere{font-size:11px!important;padding:8px 9px!important}.mblCity button{font-size:12px!important;padding:8px 10px!important}}';document.head.appendChild(s)})();
var oldShow=window.show;window.show=function(id){if(oldShow)oldShow(id);setTimeout(apply,80);setTimeout(apply,300)}
var oldHere=window.popupHere||window.checkinAction;window.popupHere=async function(id){if(oldHere)await oldHere(id);setTimeout(updateWhere,200);setTimeout(apply,250)}
var oldNot=window.popupNotHere||window.leaveVenue;window.popupNotHere=async function(id){if(oldNot)await oldNot(id);setTimeout(updateWhere,200);setTimeout(apply,250)}
setTimeout(apply,150);setTimeout(apply,800);setTimeout(apply,1800);setInterval(apply,1500);
})();