(function(){
if(window.__messagesPatch)return;window.__messagesPatch=1;
var API=window.API||'https://bztigwfnenwosulhxrxo.supabase.co/rest/v1/';
var KEY=window.KEY||'sb_publishable_P76ca2ta_N7PWpA_Wm6lTw__DEzK19l';
function q(id){return document.getElementById(id)}
function esc(s){return String(s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function clean(s){return String(s||'').toLowerCase().replace(/[^a-z0-9_]/g,'').slice(0,20)}
function safe(s){return String(s||'').replace(/[,()]/g,'')}
function arr(s){return '{'+String(s||'').split(',').map(x=>x.trim().replace(/[{}]/g,'')).filter(Boolean).join(',')+'}'}
function prof(){try{return JSON.parse(localStorage.ca_profile||'{}')}catch(e){return {}}}
function setProf(p){localStorage.ca_profile=JSON.stringify(p)}
function device(){let d=localStorage.ca_device_stable;if(!d){d='dev_'+Math.random().toString(36).slice(2)+'_'+Date.now();localStorage.ca_device_stable=d}return d}
window.dev=device;
async function caApi(path,params,opt){let u=new URL(API+path);Object.keys(params||{}).forEach(k=>u.searchParams.set(k,params[k]));let h={apikey:KEY,Authorization:'Bearer '+KEY,Prefer:'return=representation'};h['Content-Type']='application/json';let r=await fetch(u,{method:opt&&opt.method||'GET',headers:h,body:opt&&opt.body?JSON.stringify(opt.body):undefined});let t=await r.text();let d=t?JSON.parse(t):null;if(!r.ok)throw Error(d&&d.message||t||r.statusText);return d}
async function sync(){let p=prof();if(!p.name||!p.user||!p.gender)throw Error('Profil eksik');return caApi('rpc/upsert_device_profile_v5',{}, {method:'POST',body:{p_device_id:device(),p_username:p.user,p_display_name:p.name,p_age:parseInt(p.age||0)||null,p_height_cm:null,p_weight_kg:null,p_gender:p.gender,p_bio:p.bio||'',p_interests:arr(p.interests),p_instagram:'',p_photo_url:p.photo||''}})}
window.syncProfile=sync;
window.ensureProfile=async function(){let p=prof();if(!p.name||!p.user||!p.gender){show('profile');alert('Önce profil + benzersiz kullanıcı adı kaydet.');throw Error('Profil eksik')}await sync()};
window.saveProfile=async function(){let old=prof();let p={user:clean((q('loginUser').value||'')),name:(q('profName').value||'').trim(),gender:(q('profGender').value||'').trim(),age:(q('profAge').value||'').trim(),bio:(q('profBio').value||'').trim(),interests:(q('profInterests').value||'').trim(),photo:old.photo||''};let out=q('profileSaved');if(p.user.length<3){out.className='bad';out.innerHTML='Kullanıcı adı en az 3 karakter olmalı.';return}if(!p.name||!p.gender){out.className='bad';out.innerHTML='Ad ve Erkek/Kadın zorunlu.';return}out.className='warn';out.innerHTML='Kaydediliyor...';try{setProf(p);await sync();out.className='ok';out.innerHTML='Profil kaydedildi. @'+esc(p.user)+' artık sana özel.';if(window.renderProfile)renderProfile(false)}catch(e){out.className='bad';out.innerHTML=e.message.includes('alinmis')||e.message.includes('alınmış')?'Bu kullanıcı adı zaten alınmış. Başka ad dene.':'DB kaydı olmadı: '+esc(e.message)}};
function av(src){return src?`<img class='avatar small' src='${esc(src)}'>`:`<div class='avatar small'>◇</div>`}
function ready(){let p=prof();return !!(p.name&&p.user&&p.gender)}
let help=q('help'),btn=q('bhelp');
if(btn)btn.innerHTML='<span>✉</span>Mesajlar';
if(help)help.innerHTML=`<h2>Mesajlar</h2><div id='msgGate' class='warn'>Mesajlar için önce profilini ve benzersiz kullanıcı adını kaydet.</div><div class='card'><b>Kullanıcı adıyla ara</b><input id='msgSearch' placeholder='@kullanıcıadı yaz' oninput='msgSearchSoon()'><div id='msgSearchResults' class='meta'>İsim yazınca sonuçlar burada çıkar.</div></div><h3>Davetler</h3><div id='msgRequests'></div><h3>Sohbetler</h3><div id='msgChats'></div><div id='msgChatBox' class='card' style='display:none'></div>`;
var oldShow=window.show;
window.show=function(id){oldShow(id);if(id==='help')setTimeout(renderMsg,0)};
let timer=null,currentRoom=null;
window.msgSearchSoon=function(){clearTimeout(timer);timer=setTimeout(searchUsers,300)};
async function searchUsers(){if(!ready()){q('msgSearchResults').innerHTML=`<div class='warn'>Önce profilini kaydet.</div>`;return}let s=clean((q('msgSearch').value||''));if(s.length<2){q('msgSearchResults').innerHTML=`<span class='meta'>En az 2 karakter yaz.</span>`;return}q('msgSearchResults').innerHTML=`<div class='warn'>Aranıyor...</div>`;try{let rows=await caApi('rpc/find_profiles_by_username',{}, {method:'POST',body:{p_query:s,p_my_device:device()}});if(!rows.length){q('msgSearchResults').innerHTML=`<div class='warn'>Kullanıcı bulunamadı.</div>`;return}q('msgSearchResults').innerHTML=rows.map(u=>`<div class='card person'>${av(u.photo_url)}<div class='personMain'><b>${esc(u.display_name)}</b><br><span class='pill'>@${esc(u.username)}</span><p>${esc(u.bio||'Bio yok')}</p><button class='btn' data-u='${esc(u.username)}' onclick='msgInvite(this.dataset.u)'>Davet gönder</button></div></div>`).join('')}catch(e){q('msgSearchResults').innerHTML=`<div class='bad'>Arama olmadı: ${esc(e.message)}</div>`}}
window.msgInvite=async function(username){try{await window.ensureProfile();let res=await caApi('rpc/room_request_a',{}, {method:'POST',body:{p_from_device:device(),p_to_username:username}});q('msgSearchResults').innerHTML=`<div class='ok'>@${esc(username)} kullanıcısına davet gönderildi.</div>`;if(res&&res.room_id)openChat(res.room_id,username);await loadRequests()}catch(e){q('msgSearchResults').innerHTML=`<div class='bad'>Davet gitmedi: ${esc(e.message)}</div>`}};
async function profileMap(devs){devs=[...new Set(devs.filter(Boolean))];if(!devs.length)return {};let rows=await caApi('profiles',{device_id:'in.('+devs.map(safe).join(',')+')',select:'device_id,username,display_name,photo_url'});let m={};rows.forEach(p=>m[p.device_id]=p);return m}
async function loadRequests(){try{let d=safe(device());let rows=await caApi('chat_invitations',{or:`(from_device.eq.${d},to_device.eq.${d})`,select:'*',order:'updated_at.desc'});if(!rows.length){q('msgRequests').innerHTML=`<div class='warn'>Henüz davet yok.</div>`;return}let profs=await profileMap(rows.map(r=>r.from_device===device()?r.to_device:r.from_device));q('msgRequests').innerHTML=rows.map(r=>{let od=r.from_device===device()?r.to_device:r.from_device,p=profs[od]||{},u=p.username||od,n=p.display_name||od;if(r.status==='pending'&&r.to_device===device())return `<div class='card person'>${av(p.photo_url)}<div class='personMain'><b>${esc(n)}</b><br><span class='pill'>@${esc(u)}</span><p>Sana sohbet daveti gönderdi.</p><button class='btn' data-id='${r.id}' data-u='${esc(u)}' onclick='msgAccept(this.dataset.id,this.dataset.u)'>Kabul et</button><button class='btn danger' data-id='${r.id}' onclick='msgReject(this.dataset.id)'>Reddet</button></div></div>`;if(r.status==='pending')return `<div class='card person'>${av(p.photo_url)}<div class='personMain'><b>${esc(n)}</b><br><span class='pill'>@${esc(u)}</span><p class='muted'>Davet gönderildi, kabul bekleniyor.</p></div></div>`;if(r.status==='accepted')return `<div class='card person'>${av(p.photo_url)}<div class='personMain'><b>${esc(n)}</b><br><span class='pill'>@${esc(u)}</span><button class='btn light' data-room='${esc(r.room_id||'')}' data-u='${esc(u)}' onclick='msgOpenChat(this.dataset.room,this.dataset.u)'>Chat aç</button></div></div>`;return `<div class='card'><span class='muted'>@${esc(u)} daveti reddedildi.</span></div>`}).join('')}catch(e){q('msgRequests').innerHTML=`<div class='bad'>Davetler yüklenmedi: ${esc(e.message)}</div>`}}
window.msgAccept=async function(id,u){try{let res=await caApi('rpc/room_accept_a',{}, {method:'POST',body:{p_request_id:id,p_my_device:device()}});await loadRequests();await loadChats();if(res&&res.room_id)openChat(res.room_id,u)}catch(e){q('msgRequests').innerHTML=`<div class='bad'>Kabul olmadı: ${esc(e.message)}</div>`}};
window.msgReject=async function(id){try{await caApi('chat_invitations',{id:'eq.'+id},{method:'PATCH',body:{status:'rejected',updated_at:new Date().toISOString()}});await loadRequests()}catch(e){q('msgRequests').innerHTML=`<div class='bad'>Reddetme olmadı: ${esc(e.message)}</div>`}};
async function loadChats(){try{let d=safe(device());let rooms=await caApi('direct_rooms',{or:`(device_a.eq.${d},device_b.eq.${d})`,select:'*',order:'created_at.desc'});if(!rooms.length){q('msgChats').innerHTML=`<div class='warn'>Henüz açık sohbet yok.</div>`;return}let profs=await profileMap(rooms.map(r=>r.device_a===device()?r.device_b:r.device_a));q('msgChats').innerHTML=rooms.map(r=>{let od=r.device_a===device()?r.device_b:r.device_a,p=profs[od]||{},u=p.username||od;return `<div class='card person'>${av(p.photo_url)}<div class='personMain'><b>${esc(p.display_name||od)}</b><br><span class='pill'>@${esc(u)}</span><button class='btn light' data-room='${esc(r.id)}' data-u='${esc(u)}' onclick='msgOpenChat(this.dataset.room,this.dataset.u)'>Sohbeti aç</button></div></div>`}).join('')}catch(e){q('msgChats').innerHTML=`<div class='bad'>Sohbetler yüklenmedi: ${esc(e.message)}</div>`}}
function openChat(room,u){if(!room){q('msgChatBox').style.display='block';q('msgChatBox').innerHTML=`<div class='bad'>Chat odası henüz oluşmadı.</div>`;return}currentRoom=room;q('msgChatBox').style.display='block';q('msgChatBox').innerHTML=`<b>@${esc(u)}</b><button class='btn light' onclick='msgCloseChat()'>Kapat</button><div id='msgMsgs' class='warn'>Mesajlar yükleniyor...</div><textarea id='msgText' rows='2' placeholder='Mesaj yaz...'></textarea><button class='btn' onclick='msgSend()'>Gönder</button>`;loadMsgs()}
window.msgOpenChat=openChat;window.msgCloseChat=function(){q('msgChatBox').style.display='none';currentRoom=null};
async function loadMsgs(){try{let rows=await caApi('direct_messages',{room_id:'eq.'+currentRoom,select:'*',order:'created_at.asc'});q('msgMsgs').innerHTML=rows.length?rows.map(m=>`<div class='bubble ${m.sender_device===device()?'me':''}'><b>${esc(m.sender_name)}</b><br>${esc(m.body)}</div>`).join(''):`<div class='warn'>İlk mesajı sen yaz.</div>`}catch(e){q('msgMsgs').innerHTML=`<div class='bad'>Mesajlar gelmedi: ${esc(e.message)}</div>`}}
window.msgSend=async function(){let body=(q('msgText').value||'').trim();if(!body)return;try{await caApi('direct_messages',{}, {method:'POST',body:{room_id:currentRoom,sender_device:device(),sender_name:prof().name,body:body.slice(0,800)}});q('msgText').value='';await loadMsgs();await loadChats()}catch(e){q('msgMsgs').innerHTML+=`<div class='bad'>Mesaj gitmedi: ${esc(e.message)}</div>`}};
async function renderMsg(){if(!ready()){q('msgGate').style.display='block';q('msgRequests').innerHTML=`<div class='warn'>Önce profil sekmesinden kullanıcı adı kaydet.</div>`;q('msgChats').innerHTML='';q('msgChatBox').style.display='none';return}q('msgGate').style.display='none';try{await sync()}catch(e){}await loadRequests();await loadChats()}
window.renderMsg=renderMsg;
})();