(function(){
if(window.__mvpPatch)return;window.__mvpPatch=1;
var API=window.API||'https://bztigwfnenwosulhxrxo.supabase.co/rest/v1/';
var KEY=window.KEY||'sb_publishable_P76ca2ta_N7PWpA_Wm6lTw__DEzK19l';
function q(id){return document.getElementById(id)}
function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function clean(s){return String(s||'').toLowerCase().replace(/[^a-z0-9_]/g,'').slice(0,20)}
function safe(s){return String(s||'').replace(/[,()]/g,'')}
function getP(){try{return JSON.parse(localStorage.ca_profile||'{}')}catch(e){return {}}}
function setP(p){localStorage.ca_profile=JSON.stringify(p)}
function device(){var d=localStorage.ca_device_stable||localStorage.ca_device;if(!d){d='dev_'+Math.random().toString(36).slice(2)+'_'+Date.now()}localStorage.ca_device_stable=d;localStorage.ca_device=d;return d}
window.dev=device;
function interestsToText(x){if(Array.isArray(x))return x.join(', ');return String(x||'').replace(/[{}]/g,'').split(',').map(function(v){return v.trim()}).filter(Boolean).join(', ')}
function pgArr(s){return '{'+String(s||'').split(',').map(function(x){return x.trim().replace(/[{}",]/g,'')}).filter(Boolean).join(',')+'}'}
async function caApi(path,params,opt){var u=new URL(API+path);Object.keys(params||{}).forEach(function(k){u.searchParams.set(k,params[k])});var h={apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json',Prefer:'return=representation'};var r=await fetch(u,{method:(opt&&opt.method)||'GET',headers:h,body:opt&&opt.body?JSON.stringify(opt.body):undefined});var t=await r.text();var d=t?JSON.parse(t):null;if(!r.ok)throw Error((d&&d.message)||t||r.statusText);return d}
function addStyle(){if(q('mvpStyle'))return;var s=document.createElement('style');s.id='mvpStyle';s.textContent='.mvpHero{position:relative;overflow:hidden;border-radius:30px;padding:18px;background:radial-gradient(circle at top left,#7dd3fc,transparent 35%),linear-gradient(135deg,#075985,#0ea5e9 58%,#fb923c);color:white;box-shadow:0 22px 60px #07598545}.mvpTop{display:flex;gap:14px;align-items:center}.mvpAvatar{width:96px;height:96px;border-radius:30px;object-fit:cover;background:#e0f2fe;border:4px solid white;display:grid;place-items:center;color:#075985;font-weight:950;font-size:36px;box-shadow:0 14px 32px #0003}.mvpAvatar.sm{width:62px;height:62px;border-radius:21px;border:3px solid white;font-size:24px}.mvpName{font-size:30px;line-height:31px;font-weight:1000;letter-spacing:-.7px}.mvpUser{display:inline-flex;align-items:center;gap:5px;background:#ffffff28;border:1px solid #ffffff55;border-radius:999px;padding:7px 10px;font-weight:950;margin-top:6px}.mvpStats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:14px}.mvpStat{background:#ffffff20;border:1px solid #ffffff40;border-radius:18px;padding:10px;text-align:center;font-weight:900}.mvpEdit{background:#fff;border:1px solid #dbeafe;border-radius:26px;padding:14px;box-shadow:0 18px 44px #07598520}.mvpGrid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.mvpSearchLogin{background:#f0f9ff;border:1px dashed #38bdf8;border-radius:22px;padding:12px;margin-bottom:12px}.mvpCard{background:#fff;border:1px solid #dbeafe;border-radius:24px;padding:14px;margin:10px 0;box-shadow:0 14px 34px #07598514}.mvpPerson{display:flex;gap:12px;align-items:center}.mvpGrow{flex:1}.mvpVenueHead{background:linear-gradient(135deg,#082f49,#0ea5e9);color:white;border-radius:28px;padding:16px;box-shadow:0 16px 40px #07598535}.mvpVenueTitle{font-size:26px;font-weight:1000;letter-spacing:-.5px}.mvpPill{display:inline-block;border-radius:999px;background:#e0f2fe;color:#075985;padding:7px 10px;margin:4px 4px 0 0;font-size:12px;font-weight:950}.mvpVenueHead .mvpPill{background:#ffffff25;color:white;border:1px solid #ffffff50}.mvpBtnRow{display:grid;grid-template-columns:1fr 1fr;gap:8px}.danger{background:#fee2e2!important;color:#991b1b!important}.bubble{max-width:78%;background:#e0f2fe;border-radius:18px;padding:10px 12px;margin:7px 0}.bubble.me{margin-left:auto;background:#dcfce7}.mvpMini{color:#64748b;font-size:12px;font-weight:800}.mvpBigInput{font-size:16px;font-weight:850}.leaflet-popup-content button{border:0;border-radius:999px;padding:9px 12px;margin:4px;background:#0ea5e9;color:white;font-weight:900}.leaflet-popup-content button.alt{background:#e0f2fe;color:#075985}';document.head.appendChild(s)}
function avatar(src,small){return src?'<img class="mvpAvatar '+(small?'sm':'')+'" src="'+esc(src)+'">':'<div class="mvpAvatar '+(small?'sm':'')+'">◇</div>'}
async function syncProfile(){var p=getP();if(!p.name||!p.user||!p.gender)throw Error('Profil eksik');return caApi('rpc/upsert_device_profile_v5',{}, {method:'POST',body:{p_device_id:device(),p_username:p.user,p_display_name:p.name,p_age:parseInt(p.age||0)||null,p_height_cm:null,p_weight_kg:null,p_gender:p.gender,p_bio:p.bio||'',p_interests:pgArr(p.interests),p_instagram:p.instagram||'',p_photo_url:p.photo||''}})}
window.syncProfile=syncProfile;
window.ensureProfile=async function(){var p=getP();if(!p.name||!p.user||!p.gender){show('profile');alert('Önce profilini ve kullanıcı adını kaydet.');throw Error('Profil eksik')}await syncProfile()};
window.renderProfile=function(edit){addStyle();var p=getP(),has=!!(p.name&&p.user);var box=q('profile');if(!box)return;box.innerHTML='<h2>Profil</h2><div id="mvpProfileView"></div><div id="mvpProfileEdit" class="mvpEdit"></div>';var view=q('mvpProfileView'),form=q('mvpProfileEdit');if(has&&!edit){var chips=interestsToText(p.interests).split(',').map(function(x){return x.trim()}).filter(Boolean).map(function(x){return '<span class="mvpPill">'+esc(x)+'</span>'}).join('');view.innerHTML='<div class="mvpHero"><div class="mvpTop">'+avatar(p.photo,false)+'<div><div class="mvpName">'+esc(p.name)+'</div><div class="mvpUser">@'+esc(p.user)+'</div></div></div><p>'+esc(p.bio||'Bio eklenmedi')+'</p><div>'+chips+'</div><div class="mvpStats"><div class="mvpStat">'+esc(p.gender||'?')+'<br><small>Cinsiyet</small></div><div class="mvpStat">'+esc(p.age||'?')+'<br><small>Yaş</small></div><div class="mvpStat">Kalıcı<br><small>Hesap</small></div></div></div><button class="btn light" onclick="renderProfile(true)">Profili düzenle</button>';form.style.display='none';return}view.innerHTML=has?'<div class="ok">Profil düzenleme modu açık.</div>':'<div class="warn">Önce kalıcı hesabını oluştur veya kullanıcı adınla geri giriş yap.</div>';form.style.display='block';form.innerHTML='<div class="mvpSearchLogin"><b>Hesaba geri gir</b><input id="mvpLoginName" class="mvpBigInput" placeholder="kullanıcı adını yaz"><button class="btn light" onclick="mvpLogin()">Bu hesaba gir</button><div id="mvpLoginOut" class="mvpMini">Telefon değişse bile kullanıcı adını yazıp hesabını geri çekersin.</div></div><b>Profil bilgileri</b><div class="photoPick"><div id="mvpPhotoPrev">'+avatar(p.photo,false)+'</div><input id="mvpPhoto" type="file" accept="image/*"><div class="meta">Fotoğraf profil ziyaretinde ve mekân detayında görünür.</div></div><input id="mvpUser" value="'+esc(p.user||'')+'" placeholder="benzersiz kullanıcı adı"><input id="mvpName" value="'+esc(p.name||'')+'" placeholder="Adın"><div class="mvpGrid"><select id="mvpGender"><option value="">Cinsiyet</option><option '+(p.gender==='Erkek'?'selected':'')+'>Erkek</option><option '+(p.gender==='Kadın'?'selected':'')+'>Kadın</option></select><input id="mvpAge" type="number" value="'+esc(p.age||'')+'" placeholder="Yaş"></div><textarea id="mvpBio" rows="3" placeholder="Kısa bio">'+esc(p.bio||'')+'</textarea><input id="mvpInterests" value="'+esc(interestsToText(p.interests))+'" placeholder="İlgi alanları: spor, müzik, deniz"><button class="btn" onclick="mvpSaveProfile()">Profili kaydet</button><div id="mvpSaveOut"></div>';var ph=q('mvpPhoto');if(ph)ph.onchange=function(){var f=this.files&&this.files[0];if(!f)return;var r=new FileReader();r.onload=function(){var np=getP();np.photo=r.result;setP(np);renderProfile(true)};r.readAsDataURL(f)}};
window.mvpSaveProfile=async function(){var out=q('mvpSaveOut');var old=getP();var p={user:clean(q('mvpUser').value),name:(q('mvpName').value||'').trim(),gender:(q('mvpGender').value||'').trim(),age:(q('mvpAge').value||'').trim(),bio:(q('mvpBio').value||'').trim(),interests:(q('mvpInterests').value||'').trim(),photo:old.photo||''};if(p.user.length<3){out.className='bad';out.innerHTML='Kullanıcı adı en az 3 karakter olmalı.';return}if(!p.name||!p.gender){out.className='bad';out.innerHTML='Ad ve cinsiyet zorunlu.';return}out.className='warn';out.innerHTML='Kaydediliyor...';setP(p);try{await syncProfile();out.className='ok';out.innerHTML='Kaydedildi. @'+esc(p.user)+' artık bu hesabın.';renderProfile(false)}catch(e){out.className='bad';out.innerHTML=(e.message.indexOf('alinmis')>-1||e.message.indexOf('alınmış')>-1)?'Bu kullanıcı adı alınmış. Başka ad dene.':'Kaydedilemedi: '+esc(e.message)}};
window.mvpLogin=async function(){var out=q('mvpLoginOut'),u=clean(q('mvpLoginName').value);if(u.length<3){out.className='bad';out.innerHTML='En az 3 karakter yaz.';return}out.className='warn';out.innerHTML='Hesap aranıyor...';try{var row=await caApi('rpc/login_profile_by_username',{}, {method:'POST',body:{p_username:u}});if(!row||!row.device_id){out.className='bad';out.innerHTML='Bu kullanıcı adıyla kayıtlı profil bulunamadı.';return}localStorage.ca_device_stable=row.device_id;localStorage.ca_device=row.device_id;setP({user:row.username,name:row.display_name,gender:row.gender,age:row.age||'',bio:row.bio||'',interests:interestsToText(row.interests),photo:row.photo_url||''});out.className='ok';out.innerHTML='Hesap yüklendi.';renderProfile(false)}catch(e){out.className='bad';out.innerHTML='Giriş olmadı: '+esc(e.message)}};
window.pinIcon=function(v){return L.divIcon({className:'pin',html:'<div class="pinb">'+(v.emoji||'📍')+'<br><small>'+esc(v.name)+'</small></div><div class="cnt">'+Number(v.live_count||0)+'</div>',iconSize:[86,60],iconAnchor:[43,60],popupAnchor:[0,-60]})};
window.loadVenues=async function(){addStyle();try{window.venues=await caApi('rpc/venues_with_counts',{}, {method:'POST'});if(!window.map){window.map=L.map('map').setView([38.315,26.342],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19}).addTo(window.map)}window.map.eachLayer(function(l){if(l instanceof L.Marker)window.map.removeLayer(l)});window.venues.forEach(function(v){if(!v.lat||!v.lng)return;var pop='<b>'+esc(v.name)+'</b><br><small>'+esc(v.area||'Çeşme')+' · '+esc(v.category||'Mekân')+'</small><br><b>'+Number(v.live_count||0)+' kişi burada</b><br><button onclick="quickCheckIn(\''+esc(v.id)+'\')">Buradayım</button><button class="alt" onclick="selectVenue(\''+esc(v.id)+'\')">Detaylandır</button>';L.marker([v.lat,v.lng],{icon:pinIcon(v)}).addTo(window.map).bindPopup(pop)})}catch(e){alert('Mekânlar yüklenmedi: '+e.message)}};
window.selectVenue=function(id){addStyle();window.selected=(window.venues||[]).find(function(v){return v.id===id});if(!window.selected)return;var v=window.selected;q('venueTitle').textContent='';q('venueInfo').className='';q('venueInfo').innerHTML='<div class="mvpVenueHead"><div class="mvpVenueTitle">'+esc(v.name)+'</div><span class="mvpPill">'+esc(v.area||'Çeşme')+'</span><span class="mvpPill">'+esc(v.category||'Mekân')+'</span><span class="mvpPill">'+Number(v.live_count||0)+' kişi</span><div class="mvpBtnRow"><button class="btn warm" onclick="checkInSelected()">Buradayım</button><button class="btn light" onclick="loadPeople()">Detayları yenile</button></div><div class="mvpMini" style="color:white;margin-top:8px">Başka yer seçersen önceki konumun otomatik silinir.</div></div>';q('peopleList').innerHTML='';show('venue');loadPeople()};
window.quickCheckIn=async function(id){window.selected=(window.venues||[]).find(function(v){return v.id===id});await checkInSelected()};
window.checkInSelected=async function(){if(!window.selected){alert('Önce haritadan mekân seç.');return}try{await ensureProfile();await caApi('rpc/device_checkin',{}, {method:'POST',body:{p_device_id:device(),p_venue_id:window.selected.id}});q('venueInfo').innerHTML+='<div class="ok" style="margin-top:10px">Buradasın olarak işaretlendin. Eski mekân kaydın otomatik temizlendi.</div>';await loadVenues();await loadPeople()}catch(e){if(e.message!=='Profil eksik')alert('Check-in olmadı: '+e.message)}};
window.loadPeople=async function(){if(!window.selected)return;var box=q('peopleList');box.innerHTML='<div class="warn">Buradaki kullanıcılar yükleniyor...</div>';try{var rows=await caApi('rpc/people_at_venue_v5',{}, {method:'POST',body:{p_venue_id:window.selected.id}});window.mvpPeople=rows;if(!rows.length){box.innerHTML='<div class="warn">Şu an bu mekânda görünen kimse yok.</div>';return}box.innerHTML='<h3>Buradakiler</h3>'+rows.map(function(p,i){var me=p.device_id===device();return '<div class="mvpCard mvpPerson" onclick="visitPerson('+i+')">'+avatar(p.photo_url,true)+'<div class="mvpGrow"><b>'+esc(p.display_name)+(me?' <span class="mvpPill">sen</span>':'')+'</b><br><span class="mvpMini">@'+esc(p.username||'isimsiz')+' · '+esc(p.gender||'?')+' · '+esc(p.age||'?')+' yaş</span><p>'+esc(p.bio||'Bio yok')+'</p><button class="btn light" onclick="event.stopPropagation();visitPerson('+i+')">Profili ziyaret et</button></div></div>'}).join('')}catch(e){box.innerHTML='<div class="bad">Kullanıcılar yüklenmedi: '+esc(e.message)+'</div>'}};
window.visitPerson=function(i){var p=(window.mvpPeople||[])[i];if(!p)return;var me=p.device_id===device();var chips=interestsToText(p.interests).split(',').map(function(x){return x.trim()}).filter(Boolean).map(function(x){return '<span class="mvpPill">'+esc(x)+'</span>'}).join('');q('peopleList').innerHTML='<div class="mvpHero">'+avatar(p.photo_url,false)+'<div class="mvpName">'+esc(p.display_name)+'</div><div class="mvpUser">@'+esc(p.username||'isimsiz')+'</div><p>'+esc(p.bio||'Bio yok')+'</p><div>'+chips+'</div><div class="mvpStats"><div class="mvpStat">'+esc(p.gender||'?')+'<br><small>Cinsiyet</small></div><div class="mvpStat">'+esc(p.age||'?')+'<br><small>Yaş</small></div><div class="mvpStat">'+esc(window.selected?window.selected.name:'Mekân')+'<br><small>Burada</small></div></div></div>'+(me?'<div class="ok">Bu senin profilin.</div>':'<button class="btn" onclick="mvpInviteFromProfile(\''+esc(p.username||'')+'\')">Mesaj isteği gönder</button>')+'<button class="btn light" onclick="loadPeople()">Listeye dön</button>'};
window.mvpInviteFromProfile=async function(u){if(!u){alert('Bu kullanıcının kullanıcı adı yok.');return}if(window.msgInvite){await window.msgInvite(u);show('help');return}try{await ensureProfile();await caApi('rpc/room_request_a',{}, {method:'POST',body:{p_from_device:device(),p_to_username:u}});alert('@'+u+' kullanıcısına mesaj isteği gönderildi.')}catch(e){alert('Mesaj isteği gitmedi: '+e.message)}};
var oldShow=window.show;window.show=function(id){oldShow(id);if(id==='profile')setTimeout(function(){renderProfile(false)},0);if(id==='help'&&window.renderMsg)setTimeout(window.renderMsg,0)};
addStyle();if(q('profile'))renderProfile(false);if(window.loadVenues)loadVenues();
})();