(function(){
if(window.__popupLeavePatch)return;window.__popupLeavePatch=1;
var API='https://bztigwfnenwosulhxrxo.supabase.co/rest/v1/';
var KEY='sb_publishable_P76ca2ta_N7PWpA_Wm6lTw__DEzK19l';
function q(id){return document.getElementById(id)}
function esc(s){return String(s||'').replace(/[&<>]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[c]})}
function prof(){try{return JSON.parse(localStorage.ca_profile||'{}')}catch(e){return {}}}
function dev(){var p=prof();return p.device_id||localStorage.ca_device_stable||localStorage.ca_device||''}
async function postRpc(path,body){var r=await fetch(API+path,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json'},body:JSON.stringify(body||{})});var t=await r.text();var d=t?JSON.parse(t):null;if(!r.ok)throw Error((d&&d.message)||t||r.statusText);return d}
async function getApi(path,params){var u=new URL(API+path);Object.keys(params||{}).forEach(function(k){u.searchParams.set(k,params[k])});var r=await fetch(u,{headers:{apikey:KEY,Authorization:'Bearer '+KEY}});var t=await r.text();var d=t?JSON.parse(t):null;if(!r.ok)throw Error((d&&d.message)||t||r.statusText);return d}
function need(){var p=prof();if(!p.device_id||!p.user||!p.name){if(window.show)show('profile');alert('Once profile gir.');throw Error('no profile')}return p}
(function style(){if(q('popupLeaveStyle'))return;var s=document.createElement('style');s.id='popupLeaveStyle';s.textContent='.popBtn{border:0;border-radius:999px;padding:9px 11px;margin:4px;font-weight:1000}.popHere{background:#fb923c;color:white}.popDetail{background:#e0f2fe;color:#075985}.popLeave{background:#ef4444;color:white}.popRow{display:flex;flex-wrap:wrap;gap:4px;margin-top:6px}.notHereMsg{background:#fee2e2;color:#991b1b;border-radius:14px;padding:9px;margin:7px 0;font-weight:900}';document.head.appendChild(s)})();
window.popupLeaveVenue=async function(id){try{need();await postRpc('rpc/leave_venue_v1',{p_device_id:dev()});window.selected=null;if(q('venueInfo'))q('venueInfo').innerHTML='<div class="notHereMsg">Artik burada degilsin. Hicbir yer secili degil.</div>';if(q('peopleList'))q('peopleList').innerHTML='';if(window.loadVenues)await loadVenues();alert('Artik burada degilsin.')}catch(e){alert('Burda degilim olmadi: '+e.message)}};
window.loadVenues=async function(){try{window.venues=await postRpc('rpc/venues_with_counts',{});var m=window.map||window.map||map;if(!m){m=L.map('map').setView([38.315,26.342],12);window.map=m;map=m;L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19}).addTo(m)}m.eachLayer(function(l){if(l instanceof L.Marker)m.removeLayer(l)});window.venues.forEach(function(v){if(!v.lat||!v.lng)return;var icon=window.pinIcon?window.pinIcon(v):undefined;var html='<b>'+esc(v.name)+'</b><br><small>'+esc(v.area||'Cesme')+' · '+esc(v.category||'Mekan')+'</small><br><b>'+Number(v.live_count||0)+' kisi burada</b><div class="popRow"><button class="popBtn popHere" onclick="checkinAction(\''+esc(v.id)+'\')">Buradayim</button><button class="popBtn popDetail" onclick="selectVenue(\''+esc(v.id)+'\')">Detaylandir</button><button class="popBtn popLeave" onclick="popupLeaveVenue(\''+esc(v.id)+'\')">Burda degilim</button></div>';L.marker([v.lat,v.lng],{icon:icon}).addTo(m).bindPopup(html)})}catch(e){alert('Mekanlar yuklenmedi: '+e.message)}};
setTimeout(function(){if(window.loadVenues)loadVenues()},900);
})();