(function(){
if(window.__profilePhotosPatch)return;window.__profilePhotosPatch=1;
var API='https://bztigwfnenwosulhxrxo.supabase.co/rest/v1/';
var STORE='https://bztigwfnenwosulhxrxo.supabase.co/storage/v1';
var KEY='sb_publishable_P76ca2ta_N7PWpA_Wm6lTw__DEzK19l';
function q(id){return document.getElementById(id)}
function esc(s){return String(s||'').replace(/[&<>]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[c]})}
function prof(){try{return JSON.parse(localStorage.ca_profile||'{}')}catch(e){return {}}}
function saveProf(p){localStorage.ca_profile=JSON.stringify(p||{})}
function did(){var p=prof();return p.device_id||localStorage.ca_device_stable||localStorage.ca_device||''}
async function rpc(path,body){var r=await fetch(API+path,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json'},body:JSON.stringify(body||{})});var t=await r.text();var d=t?JSON.parse(t):null;if(!r.ok)throw Error((d&&d.message)||t||r.statusText);return d}
function css(){if(q('photoPatchStyle'))return;var s=document.createElement('style');s.id='photoPatchStyle';s.textContent='.photoPanel{background:white;border:1px solid #dbeafe;border-radius:26px;padding:14px;margin:12px 0;box-shadow:0 14px 34px rgba(2,132,199,.09)}.photoPanel h3{margin:0 0 10px;color:#075985;font-size:20px}.avatarRow{display:grid;grid-template-columns:88px 1fr;gap:12px;align-items:center}.bigAvatar{width:88px;height:88px;border-radius:28px;object-fit:cover;background:#e0f2fe;display:grid;place-items:center;font-size:28px;font-weight:1000;color:#075985;border:2px solid #bae6fd}.uploadBtn{display:inline-block;border:0;border-radius:999px;background:#0ea5e9;color:white;font-weight:1000;padding:10px 14px;margin:4px 4px 4px 0}.uploadBtn input{display:none}.galleryGrid{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-top:10px}.gallerySlot{height:100px;border-radius:18px;background:#f0f9ff;border:1px dashed #bae6fd;display:grid;place-items:center;overflow:hidden;position:relative}.gallerySlot img{width:100%;height:100%;object-fit:cover}.slotLabel{font-size:12px;font-weight:1000;color:#075985;text-align:center}.delPhoto{position:absolute;right:5px;top:5px;border:0;border-radius:999px;background:rgba(255,255,255,.9);color:#991b1b;font-weight:1000;padding:4px 7px}@media(max-width:760px){.galleryGrid{grid-template-columns:repeat(3,1fr)}.gallerySlot{height:112px}}';document.head.appendChild(s)}
async function upload(file,kind,slot){if(!file)return null;if(file.size>5242880)throw Error('Fotoğraf 5 MB üstü olmasın');var ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';var path=(did()||'anon')+'/'+kind+'-'+(slot||0)+'-'+Date.now()+'.'+ext;var r=await fetch(STORE+'/object/profile-photos/'+path,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':file.type||'image/jpeg','x-upsert':'true'},body:file});var t=await r.text();if(!r.ok)throw Error(t||'Yükleme olmadı');return STORE+'/object/public/profile-photos/'+path}
async function refreshLocal(){var d=did();if(!d)return;try{var rows=await fetch(API+'profiles?device_id=eq.'+encodeURIComponent(d)+'&select=*',{headers:{apikey:KEY,Authorization:'Bearer '+KEY}}).then(function(r){return r.json()});if(rows&&rows[0])saveProf(rows[0])}catch(e){}}
async function loadGallery(){var d=did();if(!d)return [];try{return await rpc('rpc/get_profile_photos_v1',{p_device_id:d})}catch(e){return []}}
async function renderPhotos(){css();var host=q('profile');if(!host)return;var old=q('photoPanel');if(old)old.remove();var p=prof(),d=did();if(!d)return;var panel=document.createElement('div');panel.id='photoPanel';panel.className='photoPanel';panel.innerHTML='<h3>Fotoğraflar</h3><div class="avatarRow"><div id="bigAvatar" class="bigAvatar">'+(p.photo_url?'<img style="width:100%;height:100%;object-fit:cover;border-radius:26px" src="'+esc(p.photo_url)+'">':esc((p.display_name||p.username||'P').slice(0,1).toUpperCase()))+'</div><div><b>Profil fotoğrafı</b><br><small>Ana fotoğrafın burada gözükecek.</small><br><label class="uploadBtn">Profil fotosu seç<input id="avatarInput" type="file" accept="image/*"></label></div></div><div style="margin-top:12px"><b>Galeri</b><br><small>En fazla 5 fotoğraf koyabilirsin.</small><div id="galleryGrid" class="galleryGrid"></div></div>';host.insertBefore(panel,host.firstChild);var photos=await loadGallery();var map={};photos.forEach(function(x){map[x.slot]=x.url});var grid=q('galleryGrid');grid.innerHTML=[1,2,3,4,5].map(function(i){var u=map[i];return '<div class="gallerySlot" data-slot="'+i+'">'+(u?'<img src="'+esc(u)+'"><button class="delPhoto" data-del="'+i+'">Sil</button>':'<label class="slotLabel">+ Foto '+i+'<input data-up="'+i+'" type="file" accept="image/*" style="display:none"></label>')+'</div>'}).join('');q('avatarInput').onchange=async function(){try{var url=await upload(this.files[0],'avatar',0);await rpc('rpc/set_profile_photo_v1',{p_device_id:d,p_photo_url:url});await refreshLocal();await renderPhotos()}catch(e){alert('Profil fotosu olmadı: '+e.message)}};grid.onchange=async function(e){var sl=e.target.dataset.up;if(!sl)return;try{var url=await upload(e.target.files[0],'gallery',sl);await rpc('rpc/set_gallery_photo_v1',{p_device_id:d,p_slot:Number(sl),p_photo_url:url});await refreshLocal();await renderPhotos()}catch(x){alert('Fotoğraf olmadı: '+x.message)}};grid.onclick=async function(e){var sl=e.target.dataset.del;if(!sl)return;try{await rpc('rpc/delete_gallery_photo_v1',{p_device_id:d,p_slot:Number(sl)});await refreshLocal();await renderPhotos()}catch(x){alert('Silinemedi: '+x.message)}}}
var oldRender=window.renderProfile;window.renderProfile=function(mode){if(oldRender)oldRender(mode);setTimeout(renderPhotos,200);setTimeout(renderPhotos,700)}
var oldShow=window.show;window.show=function(id){if(oldShow)oldShow(id);if(id==='profile')setTimeout(renderPhotos,250)}
setTimeout(function(){if(q('profile')&&getComputedStyle(q('profile')).display!=='none')renderPhotos()},1000);
})();