(function(){
if(window.__realMobileNav)return;window.__realMobileNav=1;
function q(id){return document.getElementById(id)}
function showTab(id){try{if(window.show)window.show(id)}catch(e){}}
function addStyle(){if(q('realMobileNavStyle'))return;var s=document.createElement('style');s.id='realMobileNavStyle';s.textContent='#realMobileNav{position:fixed!important;left:14px!important;right:14px!important;bottom:calc(118px + env(safe-area-inset-bottom))!important;z-index:2147483647!important;display:grid!important;grid-template-columns:1fr 1fr 1fr!important;gap:8px!important;padding:10px!important;border-radius:24px!important;background:rgba(7,89,133,.92)!important;box-shadow:0 18px 45px rgba(2,6,23,.35)!important;backdrop-filter:blur(18px)!important;pointer-events:auto!important;touch-action:manipulation!important}#realMobileNav button{border:0!important;border-radius:18px!important;padding:12px 7px!important;font-weight:1000!important;font-size:13px!important;background:rgba(255,255,255,.92)!important;color:#075985!important;pointer-events:auto!important;touch-action:manipulation!important}#realMobileNav button.active{background:#0ea5e9!important;color:white!important}body{padding-bottom:260px!important}@media(min-width:820px){#realMobileNav{bottom:calc(82px + env(safe-area-inset-bottom))!important;left:50%!important;right:auto!important;transform:translateX(-50%)!important;width:min(520px,calc(100vw - 28px))!important}}@media(max-height:720px){#realMobileNav{bottom:calc(132px + env(safe-area-inset-bottom))!important}}';document.head.appendChild(s)}
function build(){addStyle();var old=q('realMobileNav');if(old)return old;var nav=document.createElement('div');nav.id='realMobileNav';nav.innerHTML='<button id="rmnMap">Harita</button><button id="rmnMsg">Mesajlar</button><button id="rmnProfile">Profil</button>';document.body.appendChild(nav);q('rmnMap').onclick=function(){setActive('map');showTab('map');setTimeout(function(){if(window.loadVenues)loadVenues()},100)};q('rmnMsg').onclick=function(){setActive('help');showTab('help');setTimeout(function(){if(window.renderMsg)renderMsg()},100)};q('rmnProfile').onclick=function(){setActive('profile');showTab('profile');setTimeout(function(){if(window.renderProfile)renderProfile('login')},100)};return nav}
function setActive(id){['rmnMap','rmnMsg','rmnProfile'].forEach(function(x){var b=q(x);if(b)b.classList.remove('active')});if(id==='map'&&q('rmnMap'))q('rmnMap').classList.add('active');if(id==='help'&&q('rmnMsg'))q('rmnMsg').classList.add('active');if(id==='profile'&&q('rmnProfile'))q('rmnProfile').classList.add('active')}
function keep(){var nav=build();if(nav){nav.style.display='grid';nav.style.pointerEvents='auto'}}
var oldShow=window.show;window.show=function(id){if(oldShow)oldShow(id);setActive(id);setTimeout(keep,20)};
setTimeout(keep,100);setTimeout(keep,700);setTimeout(keep,1500);setInterval(keep,1200);
})();