(function(){
if(window.__userAddPlacePatch)return;window.__userAddPlacePatch=1;
var API='https://bztigwfnenwosulhxrxo.supabase.co/rest/v1/';
var KEY='sb_publishable_P76ca2ta_N7PWpA_Wm6lTw__DEzK19l';
function id(x){return document.getElementById(x)}
function prof(){try{return JSON.parse(localStorage.ca_profile||'{}')}catch(e){return {}}}
function dev(){var p=prof();return p.device_id||localStorage.ca_device_stable||localStorage.ca_device||''}
function city(){return localStorage.piyasa_city||'cesme'}
async function rpc(path,body){var r=await fetch(API+path,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json'},body:JSON.stringify(body||{})});var t=await r.text();var d=t?JSON.parse(t):null;if(!r.ok)throw Error((d&&d.message)||t||r.statusText);return d}
function css(){if(id('uapStyle'))return;var s=document.createElement('style');s.id='uapStyle';s.textContent='.uapBtn{position:fixed;right:16px;bottom:calc(122px + env(safe-area-inset-bottom));z-index:2147482500;border:0;border-radius:999px;background:#ef4444;color:white;font-weight:1000;padding:13px 16px;box-shadow:0 16px 34px rgba(239,68,68,.28)}.uapModal{position:fixed;inset:0;z-index:2147483647;background:rgba(15,23,42,.42);display:grid;place-items:center;padding:18px}.uapBox{width:min(430px,94vw);background:white;border:1px solid #dbeafe;border-radius:28px;padding:16px;box-shadow:0 24px 70px rgba(2,6,23,.34)}.uapBox h2{margin:0 0 8px;color:#075985}.uapBox p{margin:0 0 12px;color:#64748b;font-weight:800}.uapBox input,.uapBox select{width:100%;box-sizing:border-box;border:1px solid #dbeafe;border-radius:18px;padding:12px;margin:6px 0;font-weight:900;outline:0}.uapRow{display:grid;grid-template-columns:1fr 1fr;gap:8px}.uapActions{display:flex;gap:8px;justify-content:flex-end;margin-top:10px}.uapActions button,.uapPick{border:0;border-radius:999px;padding:11px 13px;font-weight:1000}.uapSave{background:#0ea5e9;color:white}.uapCancel{background:#fee2e2;color:#991b1b}.uapPick{background:#f0f9ff;color:#075985;width:100%;margin-top:6px}.uapHint{font-size:12px;color:#64748b;font-weight:900;background:#f8fafc;border:1px dashed #cbd5e1;border-radius:16px;padding:9px;margin-top:7px}@media(max-width:760px){.uapBtn{right:12px;bottom:calc(108px + env(safe-area-inset-bottom));padding:12px 14px;font-size:13px}}';document.head.appendChild(s)}
function mapVisible(){var m=id('map');if(!m)return false;var st=getComputedStyle(m),r=m.getBoundingClientRect();return st.display!=='none'&&r.width>100&&r.height>100}
function ensureBtn(){css();var b=id('uapBtn');if(!b){b=document.createElement('button');b.id='uapBtn';b.className='uapBtn';b.textContent='+ Yer Ekle';b.onclick=openModal;document.body.appendChild(b)}b.style.display=mapVisible()?'block':'none'}
function openModal(){css();var old=id('uapModal');if(old)old.remove();var pos={lat:'',lng:''};try{var c=(window.map||map).getCenter();pos.lat=c.lat.toFixed(6);pos.lng=c.lng.toFixed(6)}catch(e){}
var m=document.createElement('div');m.id='uapModal';m.className='uapModal';m.innerHTML='<div class="uapBox"><h2>Yer ekle</h2><p>Mekanı tam noktaya koymak için haritayı o noktanın üstüne getir veya konumunu kullan.</p><input id="uapName" placeholder="Mekan adı"><input id="uapArea" placeholder="Bölge / mahalle"><select id="uapCat"><option>Kafe</option><option>Restoran</option><option>Bar</option><option>Plaj</option><option>Sahil</option><option>AVM</option><option>Meydan</option><option>Kullanıcı Eklemesi</option></select><div class="uapRow"><input id="uapLat" value="'+pos.lat+'" placeholder="lat"><input id="uapLng" value="'+pos.lng+'" placeholder="lng"></div><button class="uapPick" id="uapCenter">Harita merkezini kullan</button><button class="uapPick" id="uapGeo">Konumumu kullan</button><div class="uapHint">İpucu: Haritada mekanı ortala, sonra “Harita merkezini kullan” de. Böylece pin denize kaymaz.</div><div class="uapActions"><button class="uapCancel" id="uapClose">Vazgeç</button><button class="uapSave" id="uapSave">Kaydet</button></div></div>';document.body.appendChild(m);id('uapClose').onclick=function(){m.remove()};id('uapCenter').onclick=function(){try{var c=(window.map||map).getCenter();id('uapLat').value=c.lat.toFixed(6);id('uapLng').value=c.lng.toFixed(6)}catch(e){alert('Harita merkezi okunamadı')}};id('uapGeo').onclick=function(){if(!navigator.geolocation){alert('Konum yok');return}navigator.geolocation.getCurrentPosition(function(p){id('uapLat').value=p.coords.latitude.toFixed(6);id('uapLng').value=p.coords.longitude.toFixed(6)},function(){alert('Konum izni verilmedi')},{enableHighAccuracy:true,timeout:10000})};id('uapSave').onclick=savePlace}
async function savePlace(){try{var name=id('uapName').value.trim(),area=id('uapArea').value.trim(),cat=id('uapCat').value,lat=parseFloat(id('uapLat').value),lng=parseFloat(id('uapLng').value);if(!name){alert('Mekan adı yaz');return}if(!isFinite(lat)||!isFinite(lng)){alert('Konum seç');return}await rpc('rpc/add_user_venue_v1',{p_device_id:dev(),p_name:name,p_area:area,p_category:cat,p_lat:lat,p_lng:lng,p_city:city()});var m=id('uapModal');if(m)m.remove();if(window.loadVenues)await loadVenues();alert('Yer eklendi')}catch(e){alert('Yer eklenmedi: '+e.message)}}
var oldShow=window.show;window.show=function(x){if(oldShow)oldShow(x);setTimeout(ensureBtn,120);setTimeout(ensureBtn,500)}
setTimeout(ensureBtn,800);setInterval(ensureBtn,1500);
})();